### ISSUE TITLE
Regression #20777: wrong line numbers diagnosed in inline asm

### ISSUE THREAD

**Issue by ibuclaw** [dlang/dmd#20982]
Example:
```
module asm1;



// Gap intentional



void main()
{
    asm { "" [; }
}
```

Reports:
```
asm1.d(1): Error: expression expected, not `;`
module asm1;
^
asm1.d(1): Error: found `End of File` when expecting `,`
module asm1;
 ^
asm1.d(1): Error: found `End of File` when expecting `]`
module asm1;
 ^
asm1.d(1): Error: found `End of File` when expecting `;`
module asm1;
 ^
```

Introduced by #20777

**Comment by dkorpel** [comment]
Do you have a test case for dmd?

**Comment by dkorpel** [comment]
Yes, `gccAsmSemantic` does `p.scanloc = s.loc;` which doesn't work anymore. I'll see if I can unittest that function.
