### ISSUE TITLE
"is not implemented" error hides semantic errors in methods

### ISSUE THREAD

**Issue by VPanteleev-S7** [dlang/dmd#21162]
```d
interface I
{
	void m();
}

final class C : I  // test.d(6): Error: class `test.C` interface function `void m()` is not implemented
{
	void hasError()
	{
		somethingCrazy(); // ... but ... no complaints about this line?
	}
}
```

When implementing a non-trivial interface, it's more useful to have semantic errors in the methods that are in the process of being implemented, rather than halting compilation simply because one method is missing.

This seems to be a regression, introduced in D 2.092.

**Comment by CyberShadow** [comment]
> This seems to be a regression, introduced in D 2.093.0.

Introduced in https://github.com/dlang/dmd/pull/11191.
