### ISSUE TITLE
[REG2.111] Indexing a *cast* AA yields no lvalue anymore

### ISSUE THREAD

**Issue by kinke** [dlang/dmd#21020]
This works with v2.110.0, but fails to compile with v2.111.0-beta.1:
```D
shared struct Queue
{
    int[int] map;
}

void main()
{
    auto queue = Queue();
    (cast(int[int]) queue.map)[1] = 2;
    assert(queue.map[1] == 2);
}
```

```
bug.d(9): Error: cannot modify expression `(cast(int[int])queue.map)[1]` because it is not an lvalue
```

**Comment by kinke** [comment]
AFAICT, the problem is that in https://github.com/dlang/dmd/blob/62a48a55e374bad61a164215d27e27a8daf0692e/compiler/src/dmd/expression.d#L3629-L3636 `e1.type.mutableOf.unSharedOf().equals(to.mutableOf().unSharedOf())` fails for `e1.type = shared(int[int])` and `to.type = int[int]` (`e1.isLvalue()` is true).

**Comment by kinke** [comment]
https://github.com/dlang/dmd/pull/21029
