### PR TITLE
Fix StorageClass type in genCfunc

### LINKED ISSUE #20991: Regression #20928: undefined reference to 'FuncDeclaration::genCfunc'
Introduced by #20928.

GDC and LDC now FTBFS because the function is missing - the signature in the C++ headers mismatches the D definition.

```
modules.cc:146:(.text+0xe9): undefined reference to `FuncDeclaration::genCfunc(Array<Parameter*>*, Type*, Identifier*, unsigned long)'
```

### PR DESCRIPTION
**Pull request by dkorpel**
Closes #20991 https://github.com/dlang/dmd/pull/20928#issuecomment-2725419714

### CODE REVIEW

**Comment by ibuclaw** [comment]
@dkorpel Maybe we could do something better here.  What about adding the C++ version to `cxxfrontend.d` instead?  GDC/LDC call `dmd::genCfunc`, and then you can mark `FuncDeclaration.genCfunc` as `extern(D)`.

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/declaration.h [hunk 1]
```diff
@@ -726,13 +726,13 @@ class FuncDeclaration : public Declaration
...
 
-    static FuncDeclaration *genCfunc(Parameters *args, Type *treturn, const char *name, StorageClass stc=0);
-    static FuncDeclaration *genCfunc(Parameters *args, Type *treturn, Identifier *id, StorageClass stc=0);
-
     virtual FuncDeclaration *toAliasFunc() { return this; }
     void accept(Visitor *v) override { v->visit(this); }
 };
 
+FuncDeclaration *genCfunc(Parameters *args, Type *treturn, const char *name, StorageClass stc=0);
+FuncDeclaration *genCfunc(Parameters *args, Type *treturn, Identifier *id, StorageClass stc=0);
```
Comment (ibuclaw) [inline compiler/src/dmd/declaration.h:734]: Missing namespace dmd?

There should bu a block at the top of this header.
