### ISSUE TITLE
[REG 2.111.0] alias before import no longer works

### ISSUE THREAD

**Issue by schveiguy** [dlang/dmd#21857]
This compiles on 2.110, but not on 2.111:

```d
alias foo = printf;
import core.stdc.stdio;
```

```
testme.d(1): Error: `printf` is not defined, perhaps `import core.stdc.stdio;` ?
alias foo = printf;
```

Reordering the statements works, as does selectively importing `printf`:

```d
alias foo = printf;
import core.stdc.stdio : printf; // this works
```

**Comment by schveiguy** [comment]
ldc 1.41.0, based on 2.111.0 for MacOS does not have the issue for some reason, but on Linux it does. I have not tested Windows.

**Comment by ibuclaw** [comment]
Could be a duplicate of any of #19325 #19717 #17982 #18145 (didn't check which one relates closest,all involve static if in an imported module)
