### ISSUE TITLE
Regression #20928: undefined reference to 'FuncDeclaration::genCfunc'

### ISSUE THREAD

**Issue by ibuclaw** [dlang/dmd#20991]
Introduced by #20928.

GDC and LDC now FTBFS because the function is missing - the signature in the C++ headers mismatches the D definition.

```
modules.cc:146:(.text+0xe9): undefined reference to `FuncDeclaration::genCfunc(Array<Parameter*>*, Type*, Identifier*, unsigned long)'
```
