### ISSUE TITLE
2.112 Not compile mixin Signal!(string, int);

### ISSUE THREAD

**Issue by MaksimAnishko** [dlang/dmd#22388]
Example code:

``` dlang
class A {
    mixin Signal!(string, int);
}
```
Output: 
/usr/include/dmd/phobos/std/signals.d(173,31): Error: `_d_toObject` matches conflicting symbols:
        Object o = _d_toObject(slot.ptr);
                              ^
/usr/include/dmd/phobos/std/signals.d(72,19):        function `std.signals._d_toObject`
extern (C) Object _d_toObject(void* p);
                  ^

**Comment by rikkimax** [comment]
Is this the entire error message?

You have shown only one proposed symbol.

**Comment by rainers** [comment]
If you add the import std.signals, the full error message is:
```
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(173): Error: `_d_toObject` matches conflicting symbols:
        Object o = _d_toObject(slot.ptr);
                              ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(72):        function `std.signals._d_toObject`
extern (C) Object _d_toObject(void* p);
                  ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\druntime\import\object.d(1612):        function `object._d_toObject`
extern(C) Object _d_toObject(return scope void* p) @nogc nothrow pure @trusted
                 ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(220): Error: `_d_toObject` matches conflicting symbols:
            Object o = _d_toObject(slot.ptr);
                                  ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(72):        function `std.signals._d_toObject`
extern (C) Object _d_toObject(void* p);
                  ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\druntime\import\object.d(1612):        function `object._d_toObject`
extern(C) Object _d_toObject(return scope void* p) @nogc nothrow pure @trusted
                 ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(273): Error: `_d_toObject` matches conflicting symbols:
                {   Object o = _d_toObject(slot.ptr);
                                          ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(72):        function `std.signals._d_toObject`
extern (C) Object _d_toObject(void* p);
                  ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\druntime\import\object.d(1612):        function `object._d_toObject`
extern(C) Object _d_toObject(return scope void* p) @nogc nothrow pure @trusted
                 ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(248): Error: `_d_toObject` matches conflicting symbols:
            if (_d_toObject(slots[i].ptr) is o)
                           ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\phobos\std\signals.d(72):        function `std.signals._d_toObject`
extern (C) Object _d_toObject(void* p);
                  ^
c:\d\dmd-2.112.0\windows\bin\..\..\src\druntime\import\object.d(1612):        function `object._d_toObject`
extern(C) Object _d_toObject(return scope void* p) @nogc nothrow pure @trusted
                 ^
test22388.d(4):        parent scope from here: `mixin Signal!(string, int)`
    mixin Signal!(string, int);
    ^
```
Works in dmd 2.111.0, so indeed a regression.

The definition of _d_toObject has been moved from rt.dcast to module object, but the declaration in std.signals is kept, but different.

**Comment by rainers** [comment]
PR https://github.com/dlang/phobos/pull/10931
