### ISSUE TITLE
`__traits(child)` handles `scope` incorrectly when implicit dereferencing is employed

### ISSUE THREAD

**Issue by SirNickolas** [dlang/dmd#21312]
```d
struct S {
    string s;
}

@safe:

string test1(scope S* p) => p.s; // OK.
string test2(scope S* p) => __traits(child, p, S.s); // Error.
string test3(scope S* p) => __traits(child, *p, S.s); // OK.
```

Compiles on DMD 2.110.0, doesn’t on DMD 2.111.0:

```
$ ./dmd -dip1000 -main bug.d
bug.d(8): Error: scope parameter `p` may not be returned
string test2(scope S* p) => __traits(child, p, S.s); // Error.
                            ^
```

`git bisect` told me af99c1e2d29731eb14b608e8b638e42292796b7d (#16719) is the culprit. Indeed, something related to escape analysis.
