### ISSUE TITLE
[REG2.059] Forward reference error with static immutable struct members

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18508]
### CC List

* Andrej Mitrovic (@AndrejMitrovic)
* Vladimir Panteleev (@CyberShadow)
* yebblies

### Description

````markdown
struct Foo {
    static immutable F = Foo();
    static immutable Foo[1] foos1 = [F];
    static immutable foos3 = [F];
}
void main() {}



DMD 2.061alpha:

Assertion failure: '0' on line 1235 in file 'glue.c'
````

**Comment by dlangBugzillaToGithub** [comment]
#### yebblies commented on 2013-01-14T02:35:29Z



````markdown
With 2.062 head it doesn't ice.

Now prints:

testx.d(3): Error: forward reference of variable F

or

testx.d(4): Error: variable testx.Foo.foos3 had semantic errors when compiling

If you move the lines around.  I suspect this is a dupe of one of the other forward reference bugs.
````

**Comment by dlangBugzillaToGithub** [comment]
#### andrej.mitrovich (@AndrejMitrovic) commented on 2013-02-09T21:55:30Z



````markdown
(In reply to comment #1)
> With 2.062 head it doesn't ice.

Current 2.062 head (b58ef83b22e4e4375e83aeb3f9e1ba18774f0688):

Without -g:
test.d(4): Error: variable test.Foo.foos3 had semantic errors when compiling

With -g crash and:
ty = 35, '_error_'
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2017-06-25T17:18:07Z



````markdown
Introduced in https://github.com/dlang/dmd/commit/92c8e7bdcc9ad100f8efca5cac1095ff255413d3
````
