### PR TITLE
fix regression in #20863 triggering an assertion if TypeInfo_AssociativeArray is misdefined

### PR DESCRIPTION
**Pull request by rainers**
Fail gracefully with empty declaration.

### CODE REVIEW

**Review by schveiguy — APPROVED** [review]
If it passes CI, probably good.

File: compiler/test/fail_compilation/test20863.d [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+/* TEST_OUTPUT:
+---
+fail_compilation\test20863.d(27): Error: no property `Entry` for type `object.TypeInfo_AssociativeArray`
+fail_compilation\test20863.d(23):        class `TypeInfo_AssociativeArray` defined here
+fail_compilation\test20863.d(27): Error: no property `aaGetHash` for type `object.TypeInfo_AssociativeArray`
+fail_compilation\test20863.d(23):        class `TypeInfo_AssociativeArray` defined here
+fail_compilation\test20863.d(27): Error: no property `aaOpEqual` for type `object.TypeInfo_AssociativeArray`
+fail_compilation\test20863.d(23):        class `TypeInfo_AssociativeArray` defined here
+fail_compilation\test20863.d(27): Error: no property `Entry` for type `object.TypeInfo_AssociativeArray`
+fail_compilation\test20863.d(23):        class `TypeInfo_AssociativeArray` defined here
```
Comment (ibuclaw) [inline compiler/test/fail_compilation/test20863.d]: Is semantic3 pass running twice on this typeinfo declaration?

**Comment by ibuclaw** [comment]
Judging from the errors, this ought to be at the top of the visit method.
```d
    override void visit(TypeInfoAssociativeArrayDeclaration ti)
    {
        if (ti.semanticRun >= PASS.semantic3)
            return;
        ti.semanticRun = PASS.semantic3;

```

**Comment by rainers** [comment]
> Judging from the errors, this ought to be at the top of the visit method.

Good point, added.

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/semantic3.d [hunk 2]
```diff
@@ -1643,19 +1647,24 @@ private extern(C++) final class Semantic3Visitor : Visitor
         // generate ti.xtoHash
         auto hashinst = makeDotExp(Identifier.idPool("aaGetHash"));
         e = expressionSemantic(hashinst, sc2);
-        assert(e.isVarExp() && e.type.isTypeFunction());
-        ti.xtoHash = e.isVarExp().var;
-        if (auto tmpl = ti.xtoHash.parent.isTemplateInstance())
-            tmpl.minst = sc2._module.importedFrom; // ensure it gets emitted
+        if (!e.isErrorExp())
+        {
+            assert(e.isVarExp() && e.type.isTypeFunction());
```
Comment (ibuclaw) [inline compiler/src/dmd/semantic3.d:1652]: I've just realised that this will still trigger an assert and ICE if druntime is seriously mismatched with the compiler by declaring these fields but of a different type.

```d
class TypeInfo_AssociativeArray
{
    alias aaOpEqual(K, V) = () => false;
    alias aaGetHash(K, V) = () => 0;
}
```

Comment (ibuclaw) [reply compiler/src/dmd/semantic3.d:1652]: #22143
