### ISSUE TITLE
[2.111.0][Regression] dassert: undefined reference to "assumeFakeAttributes"

### ISSUE THREAD

**Issue by katyukha** [dlang/dmd#21220]
Hello!

After migrating to 2.111.0, i got following strange link error (when running tests for my project) (on linux) ([github action](https://github.com/katyukha/peque/actions/runs/14427574034/job/40458704605)):

```d
Run dub test -b unittest-cov -c "unittestDynamic"
             Generating test runner configuration 'peque-test-unittestDynamic' for 'unittestDynamic' (library).
    Starting Performing "unittest-cov" build using /opt/hostedtoolcache/dmd/2.111.0/x64/dmd2/linux/bin64/dmd for x86_64.
    Building bindbc-common 1.0.5: building configuration [noBC]
    Building bindbc-loader 1.1.5: building configuration [noBC]
    Building peque ~dev: building configuration [peque-test-unittestDynamic]
     Linking peque-test-unittestDynamic
/usr/bin/ld: /home/runner/.dub/cache/peque/~dev/build/peque-test-unittestDynamic-unittest-cov-PR-jBBz-qNcd-iVUAuvBBQ/peque-test-unittestDynamic.o: in function `_D4core8internal7dassert__T24miniFormatFakeAttributesTbZQBdFNaNbNiNfMKxbZAya':
/opt/hostedtoolcache/dmd/2.111.0/x64/dmd2/linux/bin64/../../src/druntime/import/core/internal/dassert.d:522: undefined reference to `_D4core8internal7dassert__T20assumeFakeAttributesTPFNaNbNiNfMKxbZAyaZQBqFNaNbNiNeQBfZQBj'
collect2: error: ld returned 1 exit status
Error: undefined reference to `pure nothrow @nogc @trusted immutable(char)[] function(scope ref const(bool)) pure nothrow @nogc @safe* core.internal.dassert.assumeFakeAttributes!(immutable(char)[] function(scope ref const(bool)) pure nothrow @nogc @safe*).assumeFakeAttributes(immutable(char)[] function(scope ref const(bool)) pure nothrow @nogc @safe*)`
       perhaps `.d` files need to be added on the command line, or use `-i` to compile imports
Error: linker exited with status 1
       cc /home/runner/.dub/cache/peque/~dev/build/peque-test-unittestDynamic-unittest-cov-PR-jBBz-qNcd-iVUAuvBBQ/peque-test-unittestDynamic.o -o /home/runner/.dub/cache/peque/~dev/build/peque-test-unittestDynamic-unittest-cov-PR-jBBz-qNcd-iVUAuvBBQ/peque-test-unittestDynamic -g -m64 -Xlinker --no-as-needed -Xlinker --export-dynamic ../../../.dub/cache/bindbc-common/1.0.5/build/noBC-unittest-cov-ycRu_L4brcXvgDvk0p3yUw/libBindBC_Common.a ../../../.dub/cache/bindbc-loader/1.1.5/build/noBC-unittest-cov-JGJAaAw1klaTj2RCaZQWOQ/libBindBC_Loader.a -ldl -L/opt/hostedtoolcache/dmd/2.111.0/x64/dmd2/linux/bin64/../lib64 -Xlinker -Bstatic -lphobos2 -Xlinker -Bdynamic -lpthread -lm -lrt -ldl 
Error /opt/hostedtoolcache/dmd/2.111.0/x64/dmd2/linux/bin64/dmd failed with exit code 1.
Error: Process completed with exit code 2.
```

I am not sure what causes this error.

I use `dflags "-checkaction=context"`, but when i disable this, system just exists with `Error Program exited with code -11`

**Comment by kinke** [comment]
You were probably just lucky that you haven't needed `-allinst` so far - please check if that works around it.

The problem is that druntime and Phobos aren't prebuilt with `-checkaction=context` (the assertions are actually disabled altogether), and that doesn't play nicely with the default template-culling mechanism (without `-allinst`), which assumes that all code is compiled with the same flags (at least flags which affect template instantiations, like `-checkaction=context`).

**Comment by katyukha** [comment]
Thank you.

I have added this flag. Now it [simply fails](https://github.com/katyukha/peque/actions/runs/14448024911/job/40513381511) with `Error Program exited with code -11`. Can you suggest how to debug this (what it could be related to)?

**Comment by katyukha** [comment]
Thank you for suggestion. `-allinst` helped to resolve this.
