### PR TITLE
Move DiagnosticReporter to `errors.d`

### PR DESCRIPTION
**Pull request by jacob-carlborg**
It's more suitable located in `errors.d` since it's part of the error handling. It can also be used in other places then the lexer in the future.

Part of #9480.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Semaphore fails with 
```
Performing "debug" build using /home/runner/dlang/dmd-2.085.0/linux/bin64/dmd for x86_64.
dmd:root ~master: target for configuration "library" is up to date.
dmd:lexer ~master: building configuration "library"...
dmd:parser ~master: building configuration "library"...
dmd:frontend ~master: building configuration "library"...
lexer ~master: building configuration "application"...
lexer.d(21,32): Error: undefined identifier StderrDiagnosticReporter
/home/runner/dlang/dmd-2.085.0/linux/bin64/dmd failed with exit code 1.
```

**Comment by jacob-carlborg** [comment]
Fixed, hopefully.

It's quite annoying that there seems to be no easy way to run all the test. I'm guessing it's because different tests are run on different CI platforms.

**Comment by jacob-carlborg** [comment]
I don't see why Semaphore is failing.

**Review by PetarKirov — APPROVED** [review]

**Comment by WalterBright** [comment]
`class DiagnosticReporter` looks like hundreds of lines of code that does nothing. Why is this even there?

**Comment by WalterBright** [comment]
Apparently it was added by https://github.com/dlang/dmd/pull/9350/
