### PR TITLE
ImportC add Windows cl preprocessor #define support

### PR DESCRIPTION
**Pull request by WalterBright**
Trying it out with Microsoft's preprocessor

### CODE REVIEW

**Comment by adamdruppe** [comment]
How does that testdefine.c actually test the translation? Wouldn't the preprocessor just change that static assert to 3 == 3 without confirming the symbol is seen by D?

**Comment by adamdruppe** [comment]
cool

**Comment by WalterBright** [comment]
```
The following operation failed:
Name: checkwhitespace
```
It sure would be nice if `checkwhitespace` bothered to say which file failed. I can't find any files with tabs in them.

**Comment by WalterBright** [comment]
The code is actually working, the errors are of the form:
```
 fail_compilation\testTypeof.c(8): Error: `typeof` operator expects an expression or type name in parentheses
 fail_compilation\testTypeof.c(8): Error: identifier or `(` expected
+testTypeof.c
```
i.e. `cl` is insisting on randomly inserting the filename into stdout.

**Comment by WalterBright** [comment]
I'm lost. I don't know where `cl` is writing the `#define`'s to. It's not emitted to `stdout` (like `sppn.exe` does), and it's not in the preprocessed output file (like `cpp` does). My `cl` program is too old to support the `/PD` switch for `cl`.

Can anyone with a post-2020 `cl` investigate and let me know? Thanks!

**Comment by 12345swordy** [comment]
What is exactly preventing you from installing the latest VC Walter? You don't have to use the IDE itself in order to use the visual c++ compiler. MS does not support vc 2010 anymore.

**Comment by WalterBright** [comment]
I found the problem. Thanks @rainers for your help!

It's working now, except for some strange problem with the auto-tester that seems completely unrelated.

**Comment by RazvanN7** [comment]
@WalterBright There were some tabs introduced in https://github.com/dlang/dmd/pull/14153. But that was fixed by: https://github.com/dlang/dmd/pull/14154 . I rebased this PR and everything should be ok now.

**Review by RazvanN7 — APPROVED** [review]
