### PR TITLE
fix issue 20547, improve error messages for malformed new expressions

### PR DESCRIPTION
**Pull request by benjones**

### CODE REVIEW

File: src/dmd/expressionsem.d [hunk 1]
```diff
@@ -3706,6 +3717,15 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
 
                 Expression arg = (*exp.arguments)[i];
                 arg = resolveProperties(sc, arg);
+                if (arg.op == TOK.type)
+                {
+                    arg = resolveAliasThis(sc, arg);
+                    if (arg.op == TOK.type)
+                    {
+                        exp.error("new can only create structs, dynamic arrays or class objects, not `%s`'s", originalNewtype.toChars());
```
Comment (thewilsonator) [inline src/dmd/expressionsem.d]: what about integers, floats, and unions?

I think the message should read "cannot `new` a `%s`" or something like it.

File: src/dmd/expressionsem.d [hunk 2]
```diff
@@ -3387,7 +3388,7 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
             return setError();
         }
 
-        size_t nargs = exp.arguments ? exp.arguments.dim : 0;
+        const hasArgs = exp.arguments ? exp.arguments.dim > 0 : false;
```
Comment (WalterBright) [inline src/dmd/expressionsem.d]: This refactoring appears to have nothing to do with the PR. It also winds up computing that expression 3 times instead of once.

Comment (benjones) [reply src/dmd/expressionsem.d]: The unclear error messages were a result of calling preFunctionParameters on exp.arguments, which called expandTuples.  Moving PFP to later means args aren't expanded yet, so computing nargs here could give us the wrong answer if there are tuples.

File: src/dmd/expressionsem.d (hunk 1 above)
Comment (benjones) [reply src/dmd/expressionsem.d]: Just committed a new version... does that look better to you?

File: src/dmd/expressionsem.d [hunk 3]
```diff
@@ -1567,12 +1567,15 @@ private Expression rewriteOpAssign(BinExp exp)
...
+ * Input:
+ *      reportErrors    whether or not to report errors here.  Some callers are not
+ *                      checking actual function params, so they'll do their own error reporting
  * Output:
  *      exps[]  tuples expanded, properties resolved, rewritten in place
  * Returns:
  *      true    a semantic error occurred
  */
-private bool preFunctionParameters(Scope* sc, Expressions* exps)
+private bool preFunctionParameters(Scope* sc, Expressions* exps, bool reportErrors = true)
```
Comment (MoonlightSentinel) [inline src/dmd/expressionsem.d]:
```suggestion
private bool preFunctionParameters(Scope* sc, Expressions* exps, const bool reportErrors = true)
```

File: src/dmd/expressionsem.d [hunk 4]
```diff
@@ -3311,6 +3320,9 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
             return;
         }
 
+        //for error messages if the argument in [] is not convertible to ulong
+        auto originalNewtype = exp.newtype;
```
Comment (MoonlightSentinel) [inline src/dmd/expressionsem.d]:
```suggestion
        const originalNewtype = exp.newtype;
```

File: src/dmd/expressionsem.d [hunk 5]
```diff
@@ -3311,6 +3320,9 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
             return;
         }
 
+        //for error messages if the argument in [] is not convertible to ulong
```
Comment (MoonlightSentinel) [inline src/dmd/expressionsem.d]:
```suggestion
        //for error messages if the argument in [] is not convertible to size_t
```

File: test/fail_compilation/fail20547.d [hunk 6]
```diff
@@ -0,0 +1,13 @@
+/*
+TEST_OUTPUT:
+---
+fail_compilation/fail20547.d(11): Error: cannot create a `int[string]` with `new`
+fail_compilation/fail20547.d(12): Error: cannot create a `int[string]` with `new`
+---
+*/
+
+void main()
+{
```
Comment (MoonlightSentinel) [inline test/fail_compilation/fail20547.d]: Please add the example from bugzilla.

```suggestion
{
    int[int] a = new int[int];
```

File: src/dmd/expressionsem.d [hunk 7]
```diff
@@ -3740,7 +3767,7 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
         }
         else
         {
-            exp.error("new can only create structs, dynamic arrays or class objects, not `%s`'s", exp.type.toChars());
+            exp.error("cannot create a `%s` with `new`", exp.type.toChars());
```
Comment (MoonlightSentinel) [inline src/dmd/expressionsem.d]: The old error message was more appropriate because it explained the restrictions of `new`

File: src/dmd/expressionsem.d [hunk 8]
```diff
@@ -3369,25 +3381,40 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
...
+        //so the errors that come from preFunctionParameters are misleading
+        if (originalNewtype.ty == Tsarray)
+        {
+            if (preFunctionParameters(sc, exp.arguments, false))
+            {
+                exp.error("cannot create a `%s` with `new`", originalNewtype.toChars());
+                return setError();
+            }
+        }
+        else
```
Comment (MoonlightSentinel) [inline src/dmd/expressionsem.d]:
```suggestion
        else if (...)
```

**Review by MoonlightSentinel — CHANGES_REQUESTED** [review]
Some minor nits

File: test/fail_compilation/fail20547.d (hunk 6 above)
Comment (benjones) [reply test/fail_compilation/fail20547.d]: Since this error is detected by the parser, dmd actually stops here and doesn't report errors for b and c when a is present.  I added another test for that example.

File: src/dmd/expressionsem.d (hunk 7 above)
Comment (benjones) [reply src/dmd/expressionsem.d]: The old message missed some allowable types as @thewilsonator pointed out... Seems like an exhaustive list is a bit overwhelming, but I don't have a strong opinion either way

File: test/fail_compilation/fail20547.d (hunk 6 above)
Comment (MoonlightSentinel) [reply test/fail_compilation/fail20547.d]: Thats odd, the code below shows an error concerning the last line while hiding the two previous ones ...

```
void main()
{
    int[string] b = new int[string];
    int[string] c = new typeof(b);
    int[int] a = new int[int];
}
```

Comment (MoonlightSentinel) [reply test/fail_compilation/fail20547.d]: You're right, the first lines are resolved in semantic (probably because `string` is an alias instead of a keyword).

Comment (MoonlightSentinel) [reply test/fail_compilation/fail20547.d]: The additional file for `int[int]` is actually not needed. I missed the change in `misc_parser_err_cov1.d` which already tests an equivalent case.
Sorry for the noise.

Comment (benjones) [reply test/fail_compilation/fail20547.d]: No worries, taken out.

File: test/fail_compilation/ice11790.d [hunk 9]
```diff
@@ -1,7 +1,7 @@
 /*
 TEST_OUTPUT:
 ---
-fail_compilation/ice11790.d(8): Error: cannot pass type `string` as a function argument
```
Comment (MoonlightSentinel) [inline test/fail_compilation/ice11790.d]: You could also extend this test with the `typeof` line (and an appropriate bugzilla link) since they target the same code.
(Less file bloat in the test suite)

Comment (benjones) [reply test/fail_compilation/ice11790.d]: Seems like the wrong place to put it since it's not an ICE, but I'll see if there's another fail_compilation test that's a better home

Comment (MoonlightSentinel) [reply test/fail_compilation/ice11790.d]: Agreed, yould could also remove this in favour of your file (while keeping link to the original issue).
Just don't have multiple equivalent tests.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
The semaphore failures seem unrelated, can you  give this a force push to see if it clears?

**Comment by benjones** [comment]
Force pushes didn't seem to help.  Looks like it's failing on apt-get

File: src/dmd/expressionsem.d (hunk 7 above)
Comment (MoonlightSentinel) [reply src/dmd/expressionsem.d]: Fair enough. Maybe something like this would better but no strong opinion either.

```suggestion
            exp.error("`new`cannot create a `%s`", exp.type.toChars());
```

**Comment by Geod24** [comment]
You have to look for the red `X`, not the `O` (`X` is the failing one, `O` are failing but because they've been interrupted, as Semaphore cancels jobs as soon as one fails).

```
Performing "debug" build using /home/runner/dlang/ldc-1.19.0/bin/ldc2 for x86_64.
dmd:root ~master: building configuration "library"...
dmd:lexer ~master: building configuration "library"...
dmd:parser ~master: building configuration "library"...
dmd:frontend ~master: building configuration "library"...
avg ~master: building configuration "application"...
../../src/dmd/parse.d(9003,25): Error: no property isTypeAArray for type dmd.astbase.ASTBase.Type
avg.d(62,19): Error: template instance dmd.parse.Parser!(ASTBase) error instantiating
/home/runner/dlang/ldc-1.19.0/bin/ldc2 failed with exit code 1.
```

Looks very relevant to me.

**Comment by benjones** [comment]
Think I found the issue.  The is_____ functions from mtype.d that do casting aren't defined for ASTBase types.  Would it be worth copying those over to ASTBase in another PR?  There seem to be a handful of casts in parse.d that could be replaced

**Comment by benjones** [comment]
@thewilsonator anything else I need to do to this?
