### PR TITLE
merge stable

### LINKED ISSUE #21976: [REG 2.112.0] Array comparison performance regression
```d
import std.stdio;
import std.range;
import std.array;
import std.datetime.stopwatch;
int[] arr = iota(1000).array;
int[] arr2 = iota(1000).array;

void main()
{
    StopWatch sw;
    sw.start();
    int val;
    foreach(i; 0 .. 1_000_000) {
        val += arr == arr2;
    }
    writeln(sw.peek);
}
```

On my system, running with 2.110.0 (unoptimized):

```
54 ms, 400 μs, and 3 hnsecs
```

Running with stable (d027882ba291a31a81e26400e3119dfe459a5f98):

```
2 secs, 466 ms, 468 μs, and 5 hnsecs
```

A slowdown of about 45x.

I believe this is because we are not using memcmp anymore. See https://github.com/dlang/dmd/pull/21513

### LINKED ISSUE #22422: [REG 2.112.0] Missing _d_cast lowering for CommaExp
This regressed with v2.112.0:
```D
class C {}
class D {}

struct S {
    ~this() {}
    D opIndex(size_t) { return new D; }
}

S makeS() {
    return S();
}

C foo() {
    return cast(C) makeS()[0];
}

void main() {
    assert(foo() is null); // fails since v2.112
}
```

A fix is on its way.

### LINKED ISSUE #22480: Regression in DMD v2.112, betterC can not work with CTFE associative array any more
since `DMD v2.112` ,   CTFE associative array with `-betterC` get error:

`test.d`
```d
import testb;
@nogc nothrow:
enum a = parseAA();
extern(C) int main() {
	return 0;
}
```

`testb.di`
```d
module testb;
auto parseAA() {
	bool[string] aa ;
	aa["key"] = true;
	return true;
}
```

```sh

dmd test.d -betterC

/import/core/internal/newaa.d(362): Error: expression `new Bucket!(string, bool)[](dim)` allocates with the GC and cannot be used with switch `-fno-rtti`
        return new Bucket[dim];
               ^
/import/core/internal/newaa.d(225): Error: `TypeInfo` cannot be used with `-betterC`
        entryTI = typeid(Entry!(K, V));
                  ^
/import/core/internal/newaa.d(44):        instantiated from here: `Impl!(string, bool)`
    Impl!(K,V)* impl;
    ^
/import/core/internal/newaa.d(71):        instantiated from here: `AA!(string, bool)`
    return *(cast(AA!(substInout!K, substInout!V)*)&aa);
                  ^
/import/core/internal/newaa.d(509):        instantiated from here: `_refAA!(string, bool)`
    ref aa = _refAA!(K, V)(a);
             ^
/import/core/internal/newaa.d(489):        instantiated from here: `_aaGetX!(string, bool, string, _noV2)`
    return _aaGetX!(K, V, K2)(aax, key, found, _noV2());
```

### LINKED ISSUE #22501: [REG 2.112] GC allocation for CTFE-available static array.
Test case:
```d
struct A {
    ubyte[16] bytes;

    enum something = A(cast(ubyte[16])[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);

    @nogc nothrow pure
    bool isB() const {
        return bytes[0..12] == something.bytes[0..12];
    }
}
```

Compiles with dlang 2.111. Fails with 2.112 with error:
```
<source>(4): Error: this array literal causes a GC allocation in `@nogc` function `isB`
    enum something = A(cast(ubyte[16])[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
                                      ^
```

### LINKED ISSUE #22510: dup of inout aa broke with 2.112
```
struct S {
    int[int] aa_;
    auto aa() inout => this.aa_.dup;
}

void main() { }
```

2.110:

```
$ dmd test.d -oftestd
$
```

2.112:

```
$ dmd test.d -oftestd
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(110): Error: variable `core.internal.newaa.Entry!(int, inout(int)).Entry.value` - only parameters or stack-based variables can be `inout`
    V value;
      ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(374): Error: template instance `core.internal.newaa.Entry!(int, inout(int))` error instantiating
    Entry!(K, V)* entry;
    ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(217):        instantiated from here: `Bucket!(int, inout(int))`
    alias Bucket = .Bucket!(K, V);
                    ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(44):        instantiated from here: `Impl!(int, inout(int))`
    Impl!(K,V)* impl;
    ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(83):        instantiated from here: `AA!(int, inout(int))`
    return *(cast(inout(AA!(K, V))*)&aa);
                        ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/core/internal/newaa.d(584):        ... (1 instantiations, -v to show) ...
    auto aa = _toAA!(K, V)(a);
                          ^
dmd-2.112.0/linux/bin64/../../src/druntime/import/object.d(3072):        instantiated from here: `_aaDup!(inout(int[int]), int, inout(int))`
    return _aaDup(aa);
                 ^
test.d(3):        instantiated from here: `dup!(inout(int[int]), int, inout(int))`
    auto aa() inout => this.aa_.dup;
```

### PR DESCRIPTION
**Pull request by ibuclaw**
- fix #22386 - Indexed initialization of multi dimensional const array does not compile. (#22391)
- fix #22406 - [REG 2.112] Error: function '_d_aaLen' is not callable using argument types '(shared(int[int]))' (#22407)
- Fix #22422 - Missing _d_cast lowering for CommaExp (#22424)
- etc.linux.memoryerror: Adapt to dynamic SIGSTKSZ since glibc v2.34 (#22473)
- Bump OSX runner image to 14 (#21985)
- Bump Windows 2019 to 2022 for Azure pipelines (#22000)
- redirect output of gc/printf test to file to avoid pollution of CI logs (#22021)
- allow dmd test run arguments to be grouped with quotes so they don't generate as many combinations (#22059)
- AA: don't require TypeInfo if compiling without it (#22137)
- fix #22480 - Regression in DMD v2.112, betterC can not work with CTFE associative array any more
- fix #22510 - dup of inout aa broke with 2.112
- fix #21976: [REG 2.112.0] Array comparison performance regression
- Revert "fix #21976: [REG 2.112.0] Array comparison performance regression" (#22529)
- Fix #22544 - Cannot index AA in `with` block (#22547)
- buildAAIndexRValueX(): Avoid IdentifierExp, prefer direct VarExp (#22555)
- [stable] Fix #22543 - Cannot index AA literal in global-variable initializer (#22552)
- Fix #22501 - GC allocation for CTFE-available static array (#22571)
- avoid spurious Windows CI test failure in druntime/test/shared (#22052)
- Serialize compilation of dllgc test (#22162)
- Fix issue #22535 - [REG 2.112] Unicode symbols inside q (#22539)
- Fix #22594 - TypeInfo_Class.m_flags wrong wrt. noPointers flag when the only pointers come from tuple members (#22595)
- Fix LONG instead of LRESULT return in winuser.d (#22583)
- Fix #22625 - undefined identifier 'addr' in core.sys.posix.netinet.in_.IN6* (#22627)
- Fix Issue #22567 - alias this and nested AAs cause compiler SIGILL (#22622)
- fix issue #22556 - shared AAs with RefCounted values don't work even after removing shared
- Fix Issue 22614 - [Windows] tmpnam() in runPreprocessor generates roo… (#22615)
- bump VERSION to v2.112.1-rc.1
- Fix the fstatat declaration on macOS/x64. (#22689)
- bump VERSION to v2.112.1

### CODE REVIEW

**Comment by ibuclaw** [comment]
(I suspect merges might have not been done with `--no-ff` for a while, hence all these commits in the noise).

**Review by thewilsonator — APPROVED** [review]
