### ISSUE TITLE
Error: expression `canBitwiseHash!(...)` of type `void` does not have a boolean value

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19784]
### Description

````markdown
Also looks like a DMD problem with recursive templated types.

Partial reduction (no imports but depends on Druntime):

/////////////////// test.d ///////////////////
struct Node
{
    NodePtr[] choices;

    void visit(Handler)(Handler h)
    {
        foreach (i, f; this.tupleof)
            if (h.handle(p => &p.tupleof[i]))
                return;
    }

    mixin AutoVisitor;
}

struct NodePtr
{
    mixin AutoVisitor;

    void visit(Handler)(Handler h)
    {
        h.handle(p => p);
    }
}

template AutoVisitor()
{
    hash_t toHash()
    {
        alias T = typeof(this);
        struct Handler
        {
            T* self;
            bool handle(F)(F* delegate(T*) dg)
            {
                auto a = dg(self);
                hashOf(*a);
            }
        }
        visit!(Handler*);
    }
}
//////////////////////////////////////////////

Yields a wall of errors starting with:

.../core/internal/hash.d(503,8): Error: expression `canBitwiseHash!(NodePtr)` of type `void` does not have a boolean value

Possibly related to issue 21244.
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2020-09-23T14:58:05Z



````markdown
Amended test case which doesn't have invalid code:

/////////////////// test.d ///////////////////
struct Node
{
    NodePtr[] choices;

    void visit(Handler)(Handler h)
    {
        foreach (i, f; this.tupleof)
            if (h.handle(p => &p.tupleof[i]))
                return;
    }

    mixin AutoVisitor;
}

struct NodePtr
{
    mixin AutoVisitor;

    void visit(Handler)(Handler h)
    {
        h.handle(p => p);
    }
}

template AutoVisitor()
{
    hash_t toHash()
    {
        alias T = typeof(this);
        struct Handler
        {
            T* self;
            bool handle(F)(F* delegate(T*) dg)
            {
                auto a = dg(self);
                hashOf(*a);
                return true;
            }
        }
        visit!(Handler*)(null);
        return 0;
    }
}
//////////////////////////////////////////////

Seems to be a regression.
Introduced in https://github.com/dlang/druntime/pull/2240
````
