### ISSUE TITLE
"Error: unknown" with some bad nested struct/template declarations

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19682]
### Description

````markdown
/////////////// test.d ///////////////
struct RD
{
    struct BB
    {
        R!RD r;
    }

    Undeclared undeclared;

    struct VV
    {
        vector!int v;
    }

    struct VVV
    {
        vector!VV vv;
    }
}

struct R(T)
{
    static if (is(typeof(*p = *p)))
    {
    }

    T* p;
}


struct vector(T)
{
    Array!T array;
}

struct Array(T)
{
    struct Payload
    {
        T[] _payload;
    }

    ~this()
    {
        foreach (e; _data._payload) {}
    }

    Payload _data;

    this()()
    {
    }
}
//////////////////////////////////////

Compiler says:

$ dmd test.d 
Error: unknown, please file report on issues.dlang.org
test.d(17): Error: template instance test.vector!(VV) error instantiating
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2020-04-20T05:00:00Z



````markdown
Compilation succeeds in DMD 2.085 but not newer.

Bisecting shows that the error message begins manifesting when it was introduced ( https://github.com/dlang/dmd/pull/9425 ), however debug versions of DMD have been failing with an assertion failure before that change. The assertion failures began after https://github.com/dlang/dmd/pull/6690 .

See also issue 20753
````
