### PR TITLE
fix #21456: foreach over associative array allows incompatible types for key and value

### PR DESCRIPTION
**Pull request by rainers**
fix the lambda parameter type to correspond to key or value

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/statementsem.d [hunk 1]
```diff
@@ -4049,6 +4050,8 @@ private FuncExp foreachBodyToFunction(Scope* sc, ForeachStatement fs, TypeFuncti
             v.storage_class |= STC.temp | (stc & STC.scope_);
             Statement s = new ExpStatement(fs.loc, v);
             fs._body = new CompoundStatement(fs.loc, s, fs._body);
+            if (taa)
+                p.type = i == 1 || fs.parameters.length == 1 ? taa.nextOf() : taa.index;
```
Comment (kinke) [inline compiler/src/dmd/statementsem.d:4054]: There's a similar case for autodecoding too:
```D
void main() {
    import core.stdc.stdio;
    foreach (int i, dchar c; "abc")
        printf("%d: %c\n", i, c);
}
```

druntime's `_aApplycd2()` helper passes the pointers to (original `size_t`) index and value to the generated foreach-function. And that function then loads a 32-bit integer from the passed index pointer - so truncating to 32-bits on little-endian, but using the 32 upper bits for 64-bit big-endian targets. We have an LDC-specific fix for this (introduced in https://github.com/ldc-developers/ldc/commit/bbdf473ef0599cb238029d79aec10d8d754aa516); we might be able to fuse these 2 fixes to a single one.

Comment (kinke) [reply compiler/src/dmd/statementsem.d:4054]: => https://github.com/dlang/dmd/pull/21705
