### PR TITLE
Fix invalid characters in mangling

### PR DESCRIPTION
**Pull request by jacob-carlborg**
Running the DMD test suite with a compiler compiled in debug mode fails due to invalid characters, `-`, exist in the mangled names of some unittest blocks.

This fix centralizes the validation of mangled characters and properly replaces `-` in the mangled names of unittest blocks with `_`.

The issue was introduced in https://github.com/dlang/dmd/pull/6727.

### CODE REVIEW

**Comment by wilzbach** [comment]
CIs are failing with:

```
 ... fail_compilation/ice14424.d    -o- -unittest ()
Test failed.  The logged output:
../generated/linux/release/64/dmd -conf= -m64 -Ifail_compilation -verrors=0 -o- -unittest  -odtest_results/fail_compilation -oftest_results/fail_compilation/ice14424_0.o -c fail_compilation/ice14424.d
fail_compilation/ice14424.d(12): Error: `tuple(__unittest_fail_compilation_imports_a14424.d_3_0)` has no effect


==============================
Test failed: 
expected:
----
fail_compilation/ice14424.d(12): Error: `tuple(__unittest_fail_compilation_imports_a14424_d_3_0)` has no effect
----
actual:
----
fail_compilation/ice14424.d(12): Error: `tuple(__unittest_fail_compilation_imports_a14424.d_3_0)` has no effect
----

Makefile:204: recipe for target 'test_results/fail_compilation/ice14424.d.out' failed
```

Also mind the `d-unit` failure:

```
dunit 1.0.14: building configuration "dunit-test-library"...

source/dunit/mockable.d-mixin-156(156,78): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(156,104): Error: no identifier for declarator `.d_431_0FZ1T7method1MxFiZi`

source/dunit/mockable.d-mixin-156(157,79): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(157,105): Error: no identifier for declarator `.d_431_0FZ1T7method2MxFiZv`

source/dunit/mockable.d-mixin-156(158,97): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(158,129): Error: no identifier for declarator `.d_431_0FZ1T7method3MxFNaNbNfiZi`

source/dunit/mockable.d-mixin-156(159,98): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(159,130): Error: no identifier for declarator `.d_431_0FZ1T7method4MxFNaNbNfiZv`

source/dunit/mockable.d-mixin-156(160,100): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(160,132): Error: no identifier for declarator `.d_431_0FZ1T7method5MxFNaNbNeiZi`

source/dunit/mockable.d-mixin-156(161,101): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(161,133): Error: no identifier for declarator `.d_431_0FZ1T7method6MxFNaNbNeiZv`

source/dunit/mockable.d(111,14): Error: template instance dunit.mockable.__unittest_source_dunit_mockable.d_431_0.T.Mockable!(T).Mock!(T) error instantiating

source/dunit/mockable.d(447,23):        instantiated from here: getMock!()

source/dunit/mockable.d-mixin-156(156,78): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(156,104): Error: no identifier for declarator `.d_464_1FZ1T7method1MxFiZi`

source/dunit/mockable.d-mixin-156(157,79): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(157,105): Error: no identifier for declarator `.d_464_1FZ1T7method2MxFiZv`

source/dunit/mockable.d-mixin-156(158,97): Error: semicolon expected, not `.`

source/dunit/mockable.d-mixin-156(158,129): Error: no identifier for declarator `.d_464_1FZ1T7method3MxFNaNbNfiZi`

source/dunit/mockable.d-mixin-156(159,98): Error: semicolon expected, not `.`
```

**Comment by WalterBright** [comment]
This is a regression fix, and so should have a bugzilla entry for it.

File: src/dmd/dmangle.d [hunk 1]
```diff
@@ -584,7 +584,8 @@ public:
             assert(slice.length);
             foreach (const char c; slice)
             {
-                assert(c == '_' || c == '@' || c == '?' || c == '$' || isalnum(c) || c & 0x80);
+                assert(c.isValidMangling, "The mangled name '" ~ slice ~ "' " ~
+                    "contains an invalid character: " ~ c);
```
Comment (WalterBright) [inline src/dmd/dmangle.d]: Just leave it as:
```
assert(c.isValidMangling);
```
Anyone who cannot look at the file/line of the assert in the source code is not going to be helped by adding a message. Asserts in the compiler need to be utilitarian, so there is no incentive to leave them out of the release build.

**Comment by jacob-carlborg** [comment]
I looked at one of the failing tests in Phobos. The test inspects the demangle of a symbol. Before this PR the mangled name was `_D3std6traits32__unittest_std_traits_d_7443_193FZ3fooi`, with this PR the mangled name is `_D3std6traits32__unittest_std_traits.d_7443_193FZ3fooi`. Note the dot between `traits` and `d`. The demangler fails to demangle this name with the dot.

I did what @ibuclaw suggested on Slack and took the validation that is performed on `pragma(mangle)` and reused that, which allows a dot, while the code before replaced any dots with an underscore.

**Comment by rainers** [comment]
I would restrain from putting any special character into the mangling as this will byte you back later. For example  `@` has some special meaning on linux (version information IIRC).

So, `.` in the name should be avoided, it also doesn't fit the current mangling grammar.

The validation in dmangle is not strict enough for most D symbols and too strict for symbols in general, as any characters can creep into the mangled string as part of a template alias parameter.

**Comment by jacob-carlborg** [comment]
@rainers so perhaps we shouldn't use the exact same validation everywhere. Because with `pragma(mangle)` one should be able to use all the special symbols, in my opinion.

**Comment by rainers** [comment]
Yes, I support the comment in dymbolsem.d: "Ideally pragma(mangle) can accept a string of any content."
That would mean we cannot make any simple reliable validation, though. Running core.demangle on the mangled name might work, but will cause a bad performance penalty.

**Comment by jacob-carlborg** [comment]
I would expect `core.demangle` to only work on the D mangling, not arbitrary mangled name put in `pragma(mangle)`.

**Comment by rainers** [comment]
Yes, core.demangle doesn't work for the plain symbol set by pragma(mangle), but should be able to handle "embedded" symbols, i.e. as template alias parameters. That means it skips them correctly while decoding the rest.

**Comment by jacob-carlborg** [comment]
So what kind of validation would we like to have in the case of unittest blocks?

**Comment by rainers** [comment]
> So what kind of validation would we like to have in the case of unittest blocks?

Not sure it needs any validation, because I don't think the filename is a good identifier to begin with. It might contain relative or absolute path components which makes it rather unpredictable.

I'd recommend using the module name instead. If you want to replace the dots with an underscore and disambiguate with a module name already containing the underscore, use the mangling scheme for the module name, e.g. `3pkg7modname`.

Long term I think all those internal identifiers should follow the normal naming scheme, e.g. `3pkg7modname13__unittest_L2` or even the line number somehow not part of the identifier, but for eexample as an (template) argument. Typeinfo is another example that decodes badly.

**Comment by wilzbach** [comment]
Rebased and interestingly modifying the test was no longer required.

**Comment by jacob-carlborg** [comment]
> Rebased and interestingly modifying the test was no longer required.

The tests are still not passing. I think Atila's PR https://github.com/dlang/dmd/pull/7761 will fix this as well. But this might be good to have anyway.

**Review by wilzbach — APPROVED** [review]
Rebased again. As #7761 was merged, the modification in of `UnitTestDeclaration::createIdentifier` was no longer needed and maybe this finally passes the testsuite.

File: src/dmd/func.d [hunk 2]
```diff
@@ -22,6 +22,7 @@ import dmd.dclass;
 import dmd.declaration;
 import dmd.delegatize;
 import dmd.dinterpret;
+import dmd.dmangle;
```
Comment (Geod24) [inline src/dmd/func.d]: Doesn't seem used anywhere ?

Comment (ibuclaw) [reply src/dmd/func.d]: Indeed. Most likely the original patch had the semantic pass in this module.  Now it's been moved to dsymbolsem.

**Comment by ibuclaw** [comment]
Why is this still open?  Valid code doesn't assemble because of this.

**Comment by wilzbach** [comment]
> Why is this still open? Valid code doesn't assemble because of this.

Because it was failing on auto-tester for a long time and then was having merge conflicts.
I don't see any other reason.

**Review by Geod24 — APPROVED** [review]

**Review by JinShil — APPROVED** [review]
