### ISSUE TITLE
[REG2.095] Error on passing inout variable to function (not an lvalue)

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18118]
### CC List

* kinke
* mhh

### Description

````markdown
Testcase:
```
struct Bug(V) {
  struct Cell { }

  void getCell(ref inout(Cell) *) inout {  }

  void locate() inout {
    inout(Cell) * cell;
    getCell(cell);
  }
}

struct StructAlias(alias toRef) {}

struct S(T) {
  void foo() {}
  alias RangesList = StructAlias!(foo);
  Bug!(RangesList) bins;
}

S!uint a;
```

Compiling with dlang2.094 succeeds
Compiling with dlang2.095 gives the error:
```
bug.d(8): Error: `cast(inout(Cell)*)cell` is not an lvalue and cannot be modified
bug.d(17): Error: template instance `bug.Bug!(StructAlias!(foo))` error instantiating
bug.d(20):        instantiated from here: `S!uint`
```

A workaround to have this code compile with dlang2.100 would be appreciated.
````

**Comment by dlangBugzillaToGithub** [comment]
#### maxhaton commented on 2022-07-31T03:06:44Z



````markdown
Appears to be due to a difference in the .deco of each type despite them being the same according to toChars()
````

**Comment by dlangBugzillaToGithub** [comment]
#### johanengelen commented on 2022-07-31T10:38:54Z



````markdown
Digger says it is introduced by: https://github.com/dlang/dmd/pull/10124
````

**Comment by dlangBugzillaToGithub** [comment]
#### kinke commented on 2022-07-31T15:23:48Z



````markdown
I bet that PR just uncovered another issue, and the relevant questions IMO are:

a) Why is there a cast in the 1st place? When removing the `ref`, the `-vcg-ast` output reveals a silly

inout pure nothrow @nogc @safe void locate()
{
    inout(Cell)* cell = null;
    this.getCell(cast(inout(Cell)*)cell);
}

b) Why aren't the 2 types equivalent, where CastExp.isLvalue() would return true? https://github.com/dlang/dmd/blob/f282f98f7b8cadd4e37fb95c78d3590756f817e7/src/dmd/expression.d#L5389
````

**Comment by dlangBugzillaToGithub** [comment]
#### maxhaton commented on 2022-07-31T16:28:55Z



````markdown
I concur with both points
````
