### ISSUE TITLE
CTFE rejects modification of copied static array

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18073]
### CC List

* Vladimir Panteleev (@CyberShadow)
* RazvanN

### Description

````markdown
CTFE rejects the assignment to `copy[0]` if `arr` is const/immutable even though the static array was copied!

========================================
int countWins(const uint[2] arr)
{
	uint[2] copy = arr;
        copy[0] = 0;
	return 0;
}

enum force = countWins([4, 8]);
========================================

ctfe_copy.d(4): Error: cannot modify read-only constant `[4u, 8u]`
ctfe_copy.d(8):        called from here: `countWins([4u, 8u])`

=======================================

Introduced by https://github.com/dlang/dmd/pull/4503.
````

**Comment by dlangBugzillaToGithub** [comment]
#### razvan.nitu1305 commented on 2022-01-27T15:28:35Z



````markdown
PR: https://github.com/dlang/dmd/pull/13575
````
