### ISSUE TITLE
ddoc Error: function unmatched as result of underscore in unittest comment

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18930]
### CC List

* Ludovit Lucenic

### Description

````markdown
Generating ddoc from the following code results in an error:

code:
///
void dummy()
{
}
                                                                               
/// Testing _name
unittest
{
    assert( true );
} 

error:
$ dmd -main -D ddoc.d 
ddoc.d(2): Error: function ddoc.dummy unmatched --- in DDoc comment

The error goes away if you remove the underscore, or wrap it in quotes ("_name") and it seems to only occur in documentation comments before unittests.
````

**Comment by dlangBugzillaToGithub** [comment]
#### llucenic commented on 2015-04-08T17:48:43Z



````markdown
Same error in my case,  although, with different DDoc string. It happens after upgrading my project from 2.066 to 2.067:

/// Lexical type of a string literal
enum StringFormat : ubyte {
	/// string quoted with '"'
	Quoted = 0,
	/// wysiwyg quoted string starting with 'r"'
	RWysiwyg,
	/// wysiwyg string quoted with '`' 
(245:)	BackquoteWysiwyg,
	/// hexadecimal quoted string starting with 'x"'
	Hex
}

gives:

src/les/lexer.d(245): Error: enum member les.lexer.StringFormat.BackquoteWysiwyg unmatched --- in DDoc comment
````

**Comment by dlangBugzillaToGithub** [comment]
#### llucenic commented on 2015-04-08T17:51:26Z



````markdown
(In reply to Ludovit Lucenic from comment #1)
> Same error in my case,  although, with different DDoc string. It happens
> after upgrading my project from 2.066 to 2.067:
> 
> /// Lexical type of a string literal
> enum StringFormat : ubyte {
> 	/// string quoted with '"'
> 	Quoted = 0,
> 	/// wysiwyg quoted string starting with 'r"'
> 	RWysiwyg,
> 	/// wysiwyg string quoted with '`' 
> (245:)	BackquoteWysiwyg,
> 	/// hexadecimal quoted string starting with 'x"'
> 	Hex
> }
> 
> gives:
> 
> src/les/lexer.d(245): Error: enum member
> les.lexer.StringFormat.BackquoteWysiwyg unmatched --- in DDoc comment

I forgot to mention that changing the line 244 to:

 	/// wysiwyg string quoted with '`'`

removes the compiler error.
````

**Comment by dkorpel** [comment]
No longer happens
