### ISSUE TITLE
[REG2.112] Compile-error regression with disabled opCast and `-checkaction=context`

### ISSUE THREAD

**Issue by kinke** [dlang/dmd#21646]
```D
class C { @disable void opCast(T)(); }

void foo(Object o)
{
    auto c = new C;
    static assert(!__traits(compiles, cast(Object) c));
    assert(c is o);
}
```

This compiled fine with v2.111, but fails with current DMD nightly:
```
/dlang/dmd-nightly/linux/bin64/../../src/druntime/import/core/internal/cast_.d(162): Error: function `onlineapp.C.opCast!(void*).opCast` cannot be used because it is annotated with `@disable`
                return cast(void*)o;
                                  ^
/dlang/dmd-nightly/linux/bin64/../../src/druntime/import/core/internal/cast_.d(162): Error: cannot implicitly convert expression `o.opCast()` of type `void` to `void*`
                return cast(void*)o;
                                  ^
/dlang/dmd-nightly/linux/bin64/../../src/druntime/import/core/internal/dassert.d(329): Error: template instance `core.internal.cast_._d_cast!(C, C)` error instantiating
                return (cast() v).toString();
                               ^
/dlang/dmd-nightly/linux/bin64/../../src/druntime/import/core/internal/dassert.d(521):        instantiated from here: `miniFormat!(C)`
    alias miniT = miniFormat!T;
                  ^
/dlang/dmd-nightly/linux/bin64/../../src/druntime/import/core/internal/dassert.d(75):        instantiated from here: `miniFormatFakeAttributes!(C)`
            vals[idx] = miniFormatFakeAttributes(a[idx]);
                                                ^
onlineapp.d(7):        instantiated from here: `_d_assert_fail!(Object)`
    assert(c is o);
             ^
```

Probably introduced by https://github.com/dlang/dmd/pull/21440 or a similar PR. Caught by LDC CI which uses `-checkaction=context` for the Phobos unittests (not just for druntime), and the testcase here is a reduction of a `std.typecons` unittest.

**Comment by kinke** [comment]
Seems to boil down to this:
```D
class C {
    @disable void opCast(T)();
}

void foo(const C c) {
    auto mutable = cast() c;
}
```

This works fine in v2.111, but with the current DMD nightly:
```
core/internal/cast_.d(137): Error: function `example.C.opCast!(void*).opCast` cannot be used because it is annotated with `@disable`
        return cast(void*)o;
                          ^
core/internal/cast_.d(137): Error: cannot implicitly convert expression `o.opCast()` of type `void` to `void*`
        return cast(void*)o;
                          ^
<source>(6): Error: template instance `core.internal.cast_._d_cast!(C, C)` error instantiating
    auto mutable = cast() c;
```

**Comment by kinke** [comment]
Fixed in #22215.
