### PR TITLE
Fix #21619 - ICE core.exception.AssertError@src/dmd/pragmasem.d(456): Assertion failure

### LINKED ISSUE #21619: ICE core.exception.AssertError@src/dmd/pragmasem.d(456): Assertion failure
Reproducer
```d
void main()
{
    pragma(mangle, "")
    class BOOM { }
}
```
Backtrace
```
----------------
??:? _d_assertp [0x5ad0d261631c]
src/dmd/pragmasem.d:456 bool dmd.pragmasem.pragmaStmtSemantic(dmd.statement.PragmaStatement, dmd.dscope.Scope*) [0x5ad0d2413fda]
src/dmd/statementsem.d:1796 void dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*).visitPragma(dmd.statement.PragmaStatement) [0x5ad0d2429878]
src/dmd/statement.d:1886 void dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*).visit.VisitStatement(dmd.statement.Statement) [0x5ad0d2430684]
src/dmd/statementsem.d:3705 dmd.statement.Statement dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*) [0x5ad0d24233d3]
src/dmd/statementsem.d:155 dmd.statement.Statement dmd.statementsem.statementSemantic(dmd.statement.Statement, dmd.dscope.Scope*) [0x5ad0d24233a8]
src/dmd/statementsem.d:273 void dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*).visitCompound(dmd.statement.CompoundStatement) [0x5ad0d2423776]
src/dmd/statement.d:1886 void dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*).visit.VisitStatement(dmd.statement.Statement) [0x5ad0d24301d4]
src/dmd/statementsem.d:3705 dmd.statement.Statement dmd.statementsem.statementSemanticVisit(dmd.statement.Statement, dmd.dscope.Scope*) [0x5ad0d24233d3]
src/dmd/statementsem.d:155 dmd.statement.Statement dmd.statementsem.statementSemantic(dmd.statement.Statement, dmd.dscope.Scope*) [0x5ad0d24233a8]
src/dmd/semantic3.d:616 _ZN16Semantic3Visitor5visitEP15FuncDeclaration [0x5ad0d241a8cc]
src/dmd/func.d:1050 _ZN15FuncDeclaration6acceptEP7Visitor [0x5ad0d23a3f29]
src/dmd/semantic3.d:87 void dmd.semantic3.semantic3(dmd.dsymbol.Dsymbol, dmd.dscope.Scope*) [0x5ad0d2418fe9]
src/dmd/semantic3.d:207 _ZN16Semantic3Visitor5visitEP6Module [0x5ad0d24194c2]
src/dmd/dmodule.d:1191 _ZN6Module6acceptEP7Visitor [0x5ad0d23040e5]
src/dmd/semantic3.d:87 void dmd.semantic3.semantic3(dmd.dsymbol.Dsymbol, dmd.dscope.Scope*) [0x5ad0d2418fe9]
src/dmd/main.d:645 int dmd.main.tryMain(ulong, const(char)**, out dmd.globals.Param) [0x5ad0d22a43e5]
src/dmd/main.d:148 _Dmain [0x5ad0d22a2fb2]
```

### PR DESCRIPTION
**Pull request by ibuclaw**
pragma(mangle) in a declaration and statement context had two diverging semantics, and in some cases differing error messages for the same kind of invalid case.

This change merges the two implementation together into one function so that semantic is consistently applied.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Needs loads of tests, as I lost count of so many examples where `pragma(mangle)` violated the spec.

```d
// second argument ignored - spec says one must be symbol
pragma(mangle, "name", "eman")
struct S {}

// second argument also ignored - spec says there must be one argument only
pragma(mangle, "name", "eman")
S fun() { return S(); }

// accepts call expr with return type aggregate - this is neither a string literal nor type symbol
pragma(mangle, fun(), "name")
class C {}

// likewise, accepts var expression of type aggregate
S var;
pragma(mangle, var, "name")
class D {}

// ignored aggregate declarations wrapped around an attribute declaration
pragma(mangle, "function")
extern(C++) struct _function {}
extern(C++) void cppfun(ref _function);  // mangled as `_function&`, not `function&`.
```

File: compiler/test/compilable/test3004.d [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // https://issues.dlang.org/show_bug.cgi?id=3004
 /*
 REQUIRED_ARGS: -ignore -v
-TRANSFORM_OUTPUT: remove_lines("^(predefs|binary|version|config|DFLAG|parse|import|\(imported|semantic|entry|library|function  object|function  core|\s*$)")
+TRANSFORM_OUTPUT: remove_lines("^(predefs|binary|version|config|DFLAG|parse|inline|.*_d_newarrayU|import|\(imported|semantic|entry|library|function  object|function  core|\s*$)")
```
Comment (ibuclaw) [inline compiler/test/compilable/test3004.d:4]: This isn't related. Failure was introduced by e33c664.

File: compiler/test/fail_compilation/ice13788.d [hunk 2]
```diff
@@ -1,10 +1,10 @@
...
 TEST_OUTPUT:
 ---
-fail_compilation/ice13788.d(11): Error: pragma `mangle` - string expected for mangled name
-fail_compilation/ice13788.d(12): Error: `string` expected for mangled name, not `(1)` of type `int`
-fail_compilation/ice13788.d(13): Error: pragma `mangle` - zero-length string not allowed for mangled name
-fail_compilation/ice13788.d(14): Error: pragma `mangle` - mangled name characters can only be of type `char`
+fail_compilation/ice13788.d(11): Error: `pragma(mangle)` expects string literal argument for mangled name
+fail_compilation/ice13788.d(12): Error: `string` expected for pragma mangle argument, not `(1)` of type `int`
+fail_compilation/ice13788.d(13): Error: `pragma(mangle)` zero-length string not allowed for mangled name
+fail_compilation/ice13788.d(14): Error: `pragma(mangle)` mangled name characters can only be of type `char`
```
Comment (ibuclaw) [inline compiler/test/fail_compilation/ice13788.d:7]: pragmaStmtSemantic used `pragma(mangle)`, whilst pragmaDeclSemantic used `pragma mangle -`.

Picked the former format when merging the two implementations together.

File: compiler/test/fail_compilation/issue22682.d [hunk 3]
```diff
@@ -1,10 +1,9 @@
...
 ---
-fail_compilation/issue22682.d(14): Error: `pragma(mangle)` must be attached to a declaration
-fail_compilation/issue22682.d(15): Error: `pragma(mangle)` takes a single argument that must be a string literal
-fail_compilation/issue22682.d(16): Error: `string` expected for pragma mangle argument, not `(0)` of type `int`
-fail_compilation/issue22682.d(16): Error: `pragma(mangle)` takes a single argument that must be a string literal
-fail_compilation/issue22682.d(17): Error: `pragma(mangle)` must be attached to a declaration
+fail_compilation/issue22682.d(13): Error: `pragma(mangle)` must be attached to a declaration
+fail_compilation/issue22682.d(14): Error: `pragma(mangle)` expects string literal argument for mangled name
+fail_compilation/issue22682.d(15): Error: `string` expected for pragma mangle argument, not `(0)` of type `int`
+fail_compilation/issue22682.d(16): Error: `pragma(mangle)` must be attached to a declaration
```
Comment (ibuclaw) [inline compiler/test/fail_compilation/issue22682.d]: pragmaStmtSemantic was reporting errors on the wrong line, this is now fixed as seen by line number updates.

File: compiler/test/fail_compilation/issue22682.d [hunk 4]
```diff
@@ -1,10 +1,9 @@
...
 ---
-fail_compilation/issue22682.d(14): Error: `pragma(mangle)` must be attached to a declaration
-fail_compilation/issue22682.d(15): Error: `pragma(mangle)` takes a single argument that must be a string literal
-fail_compilation/issue22682.d(16): Error: `string` expected for pragma mangle argument, not `(0)` of type `int`
-fail_compilation/issue22682.d(16): Error: `pragma(mangle)` takes a single argument that must be a string literal
-fail_compilation/issue22682.d(17): Error: `pragma(mangle)` must be attached to a declaration
+fail_compilation/issue22682.d(13): Error: `pragma(mangle)` expects string literal argument for mangled name
+fail_compilation/issue22682.d(14): Error: `pragma(mangle)` expects string literal argument for mangled name
+fail_compilation/issue22682.d(15): Error: `string` expected for pragma mangle argument, not `(0)` of type `int`
+fail_compilation/issue22682.d(16): Error: `pragma(mangle)` expects string literal argument for mangled name
```
Comment (ibuclaw) [inline compiler/test/fail_compilation/issue22682.d:6]: New behaviour checks pragma arguments before validating whether declarations are present.

**Review by thewilsonator — APPROVED** [review]
