### ISSUE TITLE
[REG 2.112] druntime fails to build on sparcv9-sun-solaris2.11

### ISSUE THREAD

**Issue by ibuclaw** [dlang/dmd#22512]
Reduced it down to the following import in #22092.
```d
import core.sys.posix.time;
```

```
core/sys/posix/unistd.d:242:9: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
  242 |         off_t   lseek(int, off_t, int) @trusted;
      |         ^
core/sys/posix/unistd.d:242:28: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
  242 |         off_t   lseek(int, off_t, int) @trusted;
      |                            ^
core/sys/posix/unistd.d:245:32: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
  245 |         int     ftruncate(int, off_t) @trusted;
      |                                ^
core/sys/posix/unistd.d:2796:37: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
 2796 |         int         lockf(int, int, off_t);
      |                                     ^
core/sys/posix/unistd.d:2799:47: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
 2799 |         ssize_t     pread(int, void*, size_t, off_t);
      |                                               ^
core/sys/posix/unistd.d:2802:60: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
 2802 |         ssize_t     pwrite(int, const scope void*, size_t, off_t);
      |                                                            ^
core/sys/posix/unistd.d:2805:49: error: undefined identifier ‘off_t’, did you mean alias ‘off64_t’?
 2805 |         int         truncate(const scope char*, off_t);
      |                                                 ^
```
