### PR TITLE
refactor: convert cdxxx[] to CodeBuilder

### PR DESCRIPTION
**Pull request by WalterBright**
Switching the array is tedious, but repetitive. Rather than change all the functions at once, which is error-prone, I used a temporary macro CDXXX() to build wrappers. On a subsequent PR, I'll remove the wrappers and change the functions.

After that's done, we should see a performance increase in the code generator as it removes the quadratic performance of continually walking the linked list of instructions (making it linear).

### CODE REVIEW

**Review by andralex — APPROVED** [review]
Cool. Hate them commas with no space following tho.

**Comment by quickfur** [comment]
This PR makes dmd no longer compile on g++ 6.3.0:
````
  (CC)  BACK_OBJS  ddmd/backend/bcomplex.c
/usr/src/d/g++ -c -o../generated/linux/release/64/bcomplex.o -Wno-deprecated -Wstrict-aliasing -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -std=gnu++98 -Iddmd/root -Iddmd/tk -Iddmd/backend -I../generated/linux/release/64 -Iddmd -DDMDV2=1 -MMD -MF ../generated/linux/release/64/bcomplex.deps ddmd/backend/bcomplex.c
In file included from ddmd/backend/cgcod.c:2572:0:
ddmd/backend/cdxxx.c:1:39: error: conflicting declaration ‘code* (* cdxxx [181])(elem*, regm_t*)’
 code *(*cdxxx[OPMAX]) (elem *,regm_t *) =
                                       ^
In file included from ddmd/backend/cgcod.c:27:0:
ddmd/backend/code.h:239:15: note: previous declaration as ‘void (* cdxxx [])(CodeBuilder&, elem*, regm_t*)’
 extern  void(*cdxxx[])(CodeBuilder&,elem *,regm_t *);
               ^~~~~
````

**Comment by WalterBright** [comment]
Be sure cdxxx.c is deleted and regenerated with optabgen.c

**Comment by quickfur** [comment]
I did a `make clean` and got the same error.  Maybe the makefile clean rule needs updating?

**Comment by quickfur** [comment]
Manually deleting `cdxxx.c` fixed the problem. Here's a PR to fix the makefile's clean rule: #6804
