### ISSUE TITLE
[Regression master]  error "cannot get frame pointer" with AA in struct literal

### ISSUE THREAD

**Issue by rainers** [dlang/dmd#22323]
copied from https://github.com/ldc-developers/ldc/issues/5038:

compiling with `-preview=dip1000`:
```D
struct Schema { int[int] tables; }
struct S(Schema s) {
    void g() { cast(void)s.tables; }
}
auto makeSchema() => Schema([0: 0]);
alias Row = S!(makeSchema());
```
yields
```
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
```
Works with dmd 2.111.0.
