### PR TITLE
Add algorithms: filter and map, for built-in arrays

### PR DESCRIPTION
**Pull request by jacob-carlborg**
Ranges are purposely not used to simplify the implementations.

### CODE REVIEW

File: src/dmd/root/array.d [hunk 1]
```diff
@@ -591,3 +591,68 @@ unittest
...
+auto map(alias callable, T)(inout T[] array) pure nothrow @safe
+if (__traits(compiles, { auto _ = (T t) => callable(t); } ))
+{
+    if (array.length == 0)
+        return null;
+
+    alias NewElementType = ReturnType!(typeof((T t) => callable(t)));
+
+    inout(NewElementType)[] result;
+    result.reserve(array.length);
```
Comment (UplinkCoder) [inline src/dmd/root/array.d:636]: Assign to length and it'll work at ctfe as well;
and you don't have to use the concat operator further down

**Comment by UplinkCoder** [comment]
Besides, .... why?

File: src/dmd/root/array.d (hunk 1 above)
Comment (jacob-carlborg) [reply src/dmd/root/array.d:636]: `reserve` does work at CTFE. And I think it's an advantage to use concatenation instead of indexing.

**Comment by jacob-carlborg** [comment]
> Besides, .... why?

Because I need algorithms like these and I prefer to use a function that clearly shows the intent instead of using raw loops. It will also require less code compared to raw loops.

**Comment by MoonlightSentinel** [comment]
They should not have identical names as used in `std.algorithm` because
- they are eager
- they cause ambiguities if a module imports `std.algorithm.iteration` and `std.range.primitives` at the same time.

There's already a bad precedent with `write` (https://run.dlang.io/is/6RzdK5):

```
import std.stdio;
import std.file;

void main()
{
 	write("", "");   
}
```
```
onlineapp.d(6): Error: function `std.file.write!string.write` at /dlang/dmd/linux/bin64/../../src/phobos/std/file.d(740) conflicts with function `std.stdio.write!(string, string).write` at /dlang/dmd/linux/bin64/../../src/phobos/std/stdio.d(3834)
```

File: src/dmd/root/array.d [hunk 2]
```diff
@@ -591,3 +591,68 @@ unittest
...
+/**
+ * Filters the given array based on the given predicate.
+ *
+ * Returns: a new array containing only elements for which the predicate returns
+ *  `true`
+ */
+inout(T)[] filter(alias predicate, T)(inout T[] array)
+if (is(ReturnType!(typeof((T t) => predicate(t))) == bool))
+{
+    inout(T)[] result;
```
Comment (nordlow) [inline src/dmd/root/array.d:604]: Shouldn't something like `Appender!(T[]) result;` be used here instead and then return `result.data` at the end of the function?

File: src/dmd/root/array.d [hunk 3]
```diff
@@ -591,3 +591,68 @@ unittest
...
     static assert (!is(typeof(Array!(OtherStruct).init.sort!pred)));
 }
+
+/**
+ * Filters the given array based on the given predicate.
+ *
+ * Returns: a new array containing only elements for which the predicate returns
+ *  `true`
+ */
+inout(T)[] filter(alias predicate, T)(inout T[] array)
```
Comment (nordlow) [inline src/dmd/root/array.d:601]: I've seen advice on naming these functions `filtered` and `mapped` instead to make it clear that we are not returning a lazy range.

**Comment by Geod24** [comment]
I'm very much in favor of the intent, not so much in favor of the implementation. The compiler already has memory issues, adding more things that allocates doesn't strike me as the way to go.

**Comment by wilzbach** [comment]
> I'm very much in favor of the intent, not so much in favor of the implementation. The compiler already has memory issues, adding more things that allocates doesn't strike me as the way to go.

I never understood why a minimalistic version of std.range wasn't copied into the compiler.

**Comment by jacob-carlborg** [comment]
> I never understood why a minimalistic version of std.range wasn't copied into the compiler.

Not so sure it would be minimalistic.

**Comment by jacob-carlborg** [comment]
> adding more things that allocates doesn't strike me as the way to go.

It doesn't add more things if the compiler is already doing this. Only an abstraction.

File: src/dmd/root/array.d (hunk 2 above)
Comment (jacob-carlborg) [reply src/dmd/root/array.d:604]: `Appender` is part of Phobos and is not allowed in the compiler proper.

File: src/dmd/root/array.d (hunk 3 above)
Comment (jacob-carlborg) [reply src/dmd/root/array.d:601]: I disagree. Phobos contain some weird naming conventions just because initially there were some eager implementations, then someone thought it would be a good idea to add lazy implementations as well. The existing implementations could not be removed because that would breaking existing code. So new names had to be invented.

I instead prefer to look at the return type, which tells the truth.

Comment (nordlow) [reply src/dmd/root/array.d:601]: > I instead prefer to look at the return type, which tells the truth.

True, but then you can't overload the the lazy versions using the same names `filter` and `map`, right?

Would you have like Phobos to have different namings for lazy vs eager `map` and `filter`? If so what would you like that naming to look like?

Comment (jacob-carlborg) [reply src/dmd/root/array.d:601]: > True, but then you can't overload the the lazy versions using the same names filter and map, right?

No.

> Would you have like Phobos to have different namings for lazy vs eager map and filter? If so what would you like that naming to look like?

Ideally no. But Phobos only has lazy versions.

File: src/dmd/root/array.d (hunk 2 above)
Comment (nordlow) [reply src/dmd/root/array.d:604]: That's gonna create lots of garbage. I suggest we copy Appender into dmd.

Comment (jacob-carlborg) [reply src/dmd/root/array.d:604]: It's not going to create anymore garbage then it's already doing.

File: src/dmd/root/array.d (hunk 3 above)
Comment (nordlow) [reply src/dmd/root/array.d:601]: > > True, but then you can't overload the the lazy versions using the same names filter and map, right?
> 
> No.

How do you overload a lazy version on arrays?

Comment (jacob-carlborg) [reply src/dmd/root/array.d:601]: Sorry, I meant: no you cannot overload lazy and non-lazy versions using the same names.

**Comment by nordlow** [comment]
> > Besides, .... why?
> 
> Because I need algorithms like these and I prefer to use a function that clearly shows the intent instead of using raw loops. It will also require less code compared to raw loops.

Why is this better than our already proven lazy (Phobos) versions?

**Comment by jacob-carlborg** [comment]
> Why is this better than our already proven lazy (Phobos) versions?

It's less code and simpler.

**Comment by NilsLankila** [comment]
I'd like to see the additions used to a few places in a second commit. The problem is that most of the time the internal array type is used.

**Comment by PetarKirov** [comment]
> Is there any interest in merging this as is?

@jacob-carlborg I think everyone here agrees that we should have `map`, `filter,` `reduce`, etc in dmd, but the biggest point of contention is that we should have lazy instead of eager Implementations. A point could be made that `filter.array` and `map.array` would be the most common use case and so it's makes sense allocate by default, though I'm not sure if that's the case.

What can help sway the opinion in your favor is if you could find places where eager allocation is what's necessary and refactor the code to use your new functions.

> IMHO it's a good habit to name such value-returning functions `filtered` and `mapped` instead to make it clear that we are not returning a lazy range

Naming is probably the only other point of contention, if we decide to go with eager versions.
AFAIR, in https://dlang.org/phobos/std_path the functions were initially all eager and later lazy versions were added (e.g. `absolutePath` -> `asAbsolutePath`, `setExtension` -> `withExtensuon`), while in https://dlang.org/phobos/std_algorithm_iteration we mostly have one implementation (there's no eager `map`, `filter` or `uniq`, and there's no accumulating lazy version of `sum` and `mean`, AFAICS).
I think most people here would prefer if dmd starts following the Phobos strategy of the past 5-7+ years of lazy by default. So if you insist on keeping the eager design, probably the next best option is to use names like `eagerMap` and `eagerFilter`, as most D programmers would expect `map` and `filter` to be lazy.

Off topic: at work we use Typescript for some of our projects and it pains every time I look at code full of `map`, `filter`, `reduce`, knowing its doing unnecessary allocations all over the place.

**Comment by jacob-carlborg** [comment]
> I'd like to see the additions used at a few places in a second commit. 

I have a use for them (or at least one of them) in an upcoming PR [1][2]. I have had uses for them in the past.

> The problem is that most of the time the internal array type is used.

With this I was hoping to pushing more for the built-in arrays to be used. But I can add overloads for `dmd.root.array.Array`.

[1] https://github.com/jacob-carlborg/dmd/blob/f9d8476176adc0a04a54b74c1aad0292356fe4df/src/dmd/objc_glue.d#L1392
[2] https://github.com/jacob-carlborg/dmd/blob/f9d8476176adc0a04a54b74c1aad0292356fe4df/src/dmd/objc_glue.d#L1414

**Comment by jacob-carlborg** [comment]
> So if you insist on keeping the eager design

The only reason being to simplify the code and reduce the amount of code that needs to be added. You know how difficult it is to get large PRs merged. If we want the lazy versions, as in Phobos, we would need to copy half of Phobos into DMD. Then we could just as well use Phobos directly. In this PR I've added 55 lines of code. I checked in Phobos, the corresponding code will be over 600 lines of code, **without** dependencies, if all unit tests are included.

**Comment by nordlow** [comment]
> > So if you insist on keeping the eager design

As already mentioned, what about adding your eager versions under the names `mapped` and `filtered` as already mentioned?

**Comment by jacob-carlborg** [comment]
I've updated the names to `filterEagerly` and `mapEagerly` in this PR.

I've also created a bare bones implementation of `map`, `filter` and `equals` here [1]. Thoughts, would that be good enough?

[1] https://github.com/dlang/dmd/compare/master...jacob-carlborg:algorithms

**Comment by wilzbach** [comment]
> I've also created a bare bones implementation of map, filter and equals, of only 252 lines. It's available here [1]. Thoughts, would that be good enough?

Looks great! IMHO that would be more than enough and we can always add port more features/functions when necessary.
A few remarks:
- `equal`: you need to test for the emptiness of `range` after the `for` loop
Test: `equal([1, 2].map(x => x * 2), [1, 2, 3].map(x => x * 2));`
- `equal`: the second static if should be without the `else`. It's just a shortcut
Test: `equal([1, 2, 3].map(x => x * 2), [1, 2, 3].map(x => x * 2));`
- Phobos style is to `assert` in `front` and `popFront` about range `empty` (it will be removed in the release build)
- Do we need `hasLength!(Unqual!Range)`. IIRC `hasLength!(Range)` should be possible
- The `private:` covers the `front` and `popFront` declarations. On purpose?
- Maybe add `opSlice` overloads, s.t. the ranges can be saved/copied (I see that you have already used this for built-in arrays)

**Comment by jacob-carlborg** [comment]
> Looks great!

I'll make an official PR.

**Comment by jacob-carlborg** [comment]
> A few remarks

I've created an official PR: https://github.com/dlang/dmd/pull/11643. Please move your review there (I haven't made any changes yet).

**Comment by jacob-carlborg** [comment]
Superseded by https://github.com/dlang/dmd/pull/11643.
