### PR TITLE
Fix #20982 - wrong line number in iasmgcc

### LINKED ISSUE #20982: Regression #20777: wrong line numbers diagnosed in inline asm
Example:
```
module asm1;



// Gap intentional



void main()
{
    asm { "" [; }
}
```

Reports:
```
asm1.d(1): Error: expression expected, not `;`
module asm1;
^
asm1.d(1): Error: found `End of File` when expecting `,`
module asm1;
 ^
asm1.d(1): Error: found `End of File` when expecting `]`
module asm1;
 ^
asm1.d(1): Error: found `End of File` when expecting `;`
module asm1;
 ^
```

Introduced by #20777

### PR DESCRIPTION
**Pull request by dkorpel**
Still need to test this, the unittest in this module calls `parseGccAsm` but not `gccAsmSemantic`.

### CODE REVIEW

**Comment by ibuclaw** [comment]
All gdc tests pass with this now.
```
PASS: gdc.dg/asm1.d    (test for errors, line 37)
PASS: gdc.dg/asm1.d    (test for errors, line 61)
PASS: gdc.dg/asm1.d    (test for errors, line 66)
PASS: gdc.dg/asm1.d    (test for errors, line 73)
PASS: gdc.dg/asm1.d    (test for errors, line 8)
PASS: gdc.dg/asm1.d    (test for errors, line 89)
PASS: gdc.dg/asm1.d    at line 18 (test for errors, line 17)
PASS: gdc.dg/asm1.d    at line 19 (test for errors, line 17)
PASS: gdc.dg/asm1.d    at line 26 (test for errors, line 25)
PASS: gdc.dg/asm1.d    at line 27 (test for errors, line 25)
PASS: gdc.dg/asm1.d    at line 28 (test for errors, line 25)
PASS: gdc.dg/asm1.d    at line 29 (test for errors, line 25)
PASS: gdc.dg/asm1.d    at line 49 (test for errors, line 48)
PASS: gdc.dg/asm1.d    at line 50 (test for errors, line 48)
PASS: gdc.dg/asm1.d   (test for excess errors)
```

**Review by ibuclaw — APPROVED** [review]

**Comment by dkorpel** [comment]
Good, since there's no easy way to test this in dmd, let's just merge this.
