### PR TITLE
Revert "Move a couple of functions out of dsymbol.d (#15789)"

### PR DESCRIPTION
**Pull request by ibuclaw**
This reverts commit 7bff453b5e3b16c5eab2874984ed7d973a4f9e5b.

### CODE REVIEW

**Review by thewilsonator — DISMISSED** [review]
You've put a GDC tag on it this time, which is better than nothing, but I'd still like an explanation as to why this is necessary, considering that this undies progress of moving stuff out of AST and into sema. Again I suspect that the appropriate course of action here is to make this work not to  revert it.

_Please do not merge this without a satisfactory explanation_.

**Comment by ibuclaw** [comment]
```
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/mtype.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/typesem.o: in function `merge(Type*)':
/build/gcc-trunk/build.9/gcc/../../gcc/d/dmd/typesem.d:2029: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
collect2: error: ld returned 1 exit status
make: *** [../../gcc/d/Make-lang.in:236: d21] Error 1
```

**Comment by ibuclaw** [comment]
1. Don't move huge swaths of functions and their dependencies around. Move them one at a time so these can be easily bisected and reverted as-needed.
2. Don't add new global imports, use selective imports at function level.

**Comment by RazvanN7** [comment]
So the linker errors are the same as in the case of the other PR? This looks like something that is particular to the way gdc compiles the frontend.

**Comment by ibuclaw** [comment]
> So the linker errors are the same as in the case of the other PR? This looks like something that is particular to the way gdc compiles the frontend.

Modules are compiled separately, there's nothing peculiar about it.

**Comment by thewilsonator** [comment]
> Modules are compiled separately, there's nothing peculiar about it.

Clearly it is 1) different and, 2) not tested. You should set up a CI job that builds and links DMD with modules copied separately if you want to prevent this from happening again.

**Comment by ibuclaw** [comment]
> > Modules are compiled separately, there's nothing peculiar about it.
> 
> Clearly it is 1) different and, 2) not tested. You should set up a CI job that builds and links DMD with modules copied separately if you want to prevent this from happening again.

You can watch the daily builds.

https://github.com/D-Programming-GDC/gcc/actions/runs/6982207333

Downstream user noticed that it affects everything, not just the target they were bootstrapping from.  I've accounted for this and now you see everything is red.

**Comment by thewilsonator** [comment]
I meant a DMD CI job, so that it gets caught here and not later on.

**Comment by ibuclaw** [comment]
> I meant a DMD CI job, so that it gets caught here and not later on.

DMD CI is not a good yardstick for success.

**Comment by ibuclaw** [comment]
Blocked for a week, and there's [yet another pr](https://github.com/dlang/dmd/pull/15870) that pushes the diff with upstream over the 400kb limit.

**Comment by dkorpel** [comment]
> pushes the diff with upstream over the 400kb limit

What limit?

**Comment by RazvanN7** [comment]
The change is quite small in the mentioned PR, it's just that the automated generation of `frontend.h` that went crazy.

Anyway, I can put up a PR to unblock you in a way that does not undo previous work, however, since building gdc is not tested on the pipeline, I have no way of knowing it my fix actually does something.

**Comment by RazvanN7** [comment]
@ibuclaw here is an attempt at fixing the issue: https://github.com/dlang/dmd/pull/15872

**Comment by ibuclaw** [comment]
> The change is quite small in the mentioned PR, it's just that the automated generation of `frontend.h` that went crazy.
> 
> Anyway, I can put up a PR to unblock you in a way that does not undo previous work, however, since building gdc is not tested on the pipeline, I have no way of knowing it my fix actually does something.

By the way, this broke before in the same way due to functions being moved around.

https://issues.dlang.org/show_bug.cgi?id=21294  (Fix PR https://github.com/dlang/dmd/pull/11827)
https://issues.dlang.org/show_bug.cgi?id=21299  (Fix PR https://github.com/dlang/dmd/pull/11838)

**Comment by ibuclaw** [comment]
> I meant a DMD CI job, so that it gets caught here and not later on.

There's already a test in the testsuite for this - the problem is DMD has been patched to address the issue since 2.095.1.

**Comment by RazvanN7** [comment]
@ibuclaw is it ok to close this?

**Comment by ibuclaw** [comment]
> @ibuclaw is it ok to close this?

Mainline is green again.

https://github.com/D-Programming-GDC/gcc/actions/workflows/main.yml
