### ISSUE TITLE
Type comparison does not work properly with subtyping

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18553]
### CC List

* Vladimir Panteleev (@CyberShadow)
* 

### Description

````markdown
struct Tuple(Types...)
{
    alias TypeTuple = Types;
    alias TypeTuple this;
}

alias list = Tuple!int;

void main()
{
    static assert(is(list.TypeTuple[0] == int));  // ok
    pragma(msg, list[0]);  // 'int'
    static assert(is(list[0] == int));  // ng
}
````

**Comment by dlangBugzillaToGithub** [comment]
#### hsteoh commented on 2014-08-29T14:39:05Z



````markdown
git HEAD may have regressed:
------
$ dmd test.d
test.d(12): Error: no [] operator overload for type Tuple!int
test.d(12):        while evaluating pragma(msg, (Tuple!int)[0])
test.d(13): Error: static assert  (is(Tuple!int[0] == int)) is false
$
------

Note the error on line 12, which is the pragma(msg) line.
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2017-07-03T21:30:52Z



````markdown
(In reply to hsteoh from comment #1)
> git HEAD may have regressed:

Broken by https://github.com/dlang/dmd/pull/443 (issue 6798) and later fixed by https://github.com/dlang/dmd/pull/4350 (issue 14057).
````
