### ISSUE TITLE
I am working with the package tinyredis 2.1.1 and I can't compile, dmd exit with exit code 1 because EWOULDBLOCK is not defined

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19456]
### CC List

* Seb

### Description

````markdown
I am working with the package tinyredis 2.1.1 and I can't compile, dmd exit with exit code 1 because EWOULDBLOCK is not defined 

C:\Users\jakez\AppData\Local\dub\packages\tinyredis-2.1.1\tinyredis\source\tinyredis\connection.d(145,30): Error: undefined identifier EWOULDBLOCK
dmd failed with exit code 1.

I signaled it to the tinyredis developer too.

I hope this will help
````

**Comment by dlangBugzillaToGithub** [comment]
#### greensunny12 commented on 2018-07-16T09:21:46Z



````markdown
This looks like a problem with the library, not DMD.
For a good bug report, we would need to have a minimal reproducible example (try dustmite) that typically is a few lines without dependencies on external projects.
Sorry, but you might have a look at other redis projects in the meantime. Vibe.d has redis support for example.
````

**Comment by thewilsonator** [comment]
use

```
import core.stdc.errno;
```
