### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- Fix Issue 15909 - Duplicate case error reports characters as numbers
- Fix Issue 21282 - mixin of AliasSeq "cannot alias an expression" (#11814)
- Fix Issue 21283 - [C++] Wrong mangling for ref of parameter pack
- bump VERSION to v2.094.1-beta.1
- Github CI: Replace set-env with environment file
- d_do_test: Adjust object filename to match compiled modules in subdirectories
- Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()
- Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()
- bump VERSION to v2.094.1
- Fix Issue 21330 - __traits(getUnitTests) should include unittests from anonymous mixins
- Fix Issue 20324 - Calling __traits(getUnitTests) on a template causes compiler segfault
- Fix Issue 21285 - Delegate covariance broken between 2.092 and 2.094 (git master)
- Revert "Merge pull request #11381 from andralex/pool"
- Revert "Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()"
- Issue 21299: Add regression test for another undefined reference issue
- Fix Issue 21353 - 'With()' statement ignores symbol visibility in some cases
- bump VERSION to v2.094.2-beta.1

### CODE REVIEW

**Comment by kinke** [comment]
@ibuclaw: Your new `compilable/test21299d.d` (`DefaultPredicates`) test has apparently regressed for master in the meantime. :/

**Comment by ibuclaw** [comment]
I blame @Geod24 for not merging my pr when he had the chance. ;-)

**Comment by ibuclaw** [comment]
@kinke actually, it is a bad merge, the breaking change isn't reverted here for some reason.
