### ISSUE TITLE
can no longer take address or static .init of stat_t.st_mtime

### ISSUE THREAD

**Issue by huglovefan** [dlang/dmd#23857]
these two patterns used to work but they don't anymore:

```D
import core.sys.posix.sys.stat;
void main()
{
	// 1.
	stat_t sb;
	time_t* tp = &sb.st_mtime;
	// 2.
	time_t t = stat_t.st_mtime.init;
}
```

current dmd outputs:

```D
test.d(6): Error: cannot implicitly convert expression `&sb.st_mtime` of type `inout(long) delegate() inout pure nothrow @property return ref @safe` to `long*`
    time_t* tp = &sb.st_mtime;
                 ^
test.d(8): Error: calling non-static function `st_mtime` requires an instance of type `stat_t`
    time_t t = stat_t.st_mtime.init;
               ^
```

last known version where they worked was v2.111.0, non-working versions i tried are v2.112.0 through v2.113.0 and the current nightly at commit 45ee747cf9a3535277832f1137a2791f056bf691

os: x86-64 linux glibc (debian stable)

**Comment by rikkimax** [comment]
Appears to have been introduced by https://github.com/dlang/dmd/pull/21249
