### ISSUE TITLE
Spurious 'incompatible types' conversion error in 2D array intializer

### ISSUE THREAD

**Issue by dkorpel** [dlang/dmd#23900]
Requires skipping element 0, and function scope.

Expected compilable:
```D
void main()
{    
    int[3][2] color = [
            1: [255, 0, 0],
    ];
}
```

Actual output:
```
Error: incompatible types for `(0) : ([255, 0, 0])`: `int` and `int[]`
```

**Comment by dkorpel** [comment]
Introduced by https://github.com/dlang/dmd/pull/21824

**Comment by dkorpel** [comment]
Related, expected compilable:

```D
int[3][2] color = [
		0: [255, 0, 0],
		1: 0, // no error
];

void main()
{
     int[3][2] color = [
            0: [255, 0, 0],
            1: 0, // error
    ];   
}
```

So instead of a regression, you can also consider this a pre-existing bug in explicit init being uncovered and exacerbated by the new default init logic.
