### ISSUE TITLE
[REG2.099.0] Can't decide between const and non-const overload with lambda

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#18172]
### CC List

* mhh

### Description

````markdown
//////////////////////// test.d ////////////////////////
struct S
{
    void fun(scope void delegate(      int []))       {}
    void fun(scope void delegate(const(int)[])) const {}
}

unittest
{
    S s;
    s.fun((arr) {});
}
////////////////////////////////////////////////////////

Compiler says:

test.d(10): Error: `test.S.fun` called with argument types `(void)` matches both:
test.d(3):     `test.S.fun(scope void delegate(int[]) _param_0)`
and:
test.d(4):     `test.S.fun(scope void delegate(const(int)[]) _param_0) const`

Looks very similar to issue 23274, may be the same underlying bug.
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2023-06-02T16:00:44Z



````markdown
Introduced in https://github.com/dlang/dmd/pull/13267
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2023-06-02T16:13:22Z



````markdown
> called with argument types `(void)`

Misleading diagnostic, BTW. (Templates have type "void" for some D 0.0x reasons.)
````

**Comment by dlangBugzillaToGithub** [comment]
#### maxhaton commented on 2023-06-02T17:00:44Z



````markdown
Looks like it used to fail prior to 2.075.1 as well
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2023-06-02T17:04:01Z



````markdown
Yes, originally implemented in https://github.com/dlang/dmd/pull/6731
````
