### ISSUE TITLE
successful static assert can change result of compilation

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19016]
### CC List

* Vladimir Panteleev (@CyberShadow)

### Description

````markdown
This compiles successfully:

enum hasElaborateAssign(T) = is(typeof(foo!T())) || true;

//static assert(hasElaborateAssign!int);

static assert(is(typeof(foo!int())));

void foo(T)()
{
    static assert(hasElaborateAssign!T);
}


but when uncommenting the first assertion, the second assert fails with 

error test.d(5): Error: static assert (is(typeof(__error))) is false
````

**Comment by dlangBugzillaToGithub** [comment]
#### dlang-bugzilla (@CyberShadow) commented on 2015-09-01T05:44:26Z



````markdown
This appears to be a regression.

Introduced by https://github.com/D-Programming-Language/dmd/pull/544
````

**Comment by dlangBugzillaToGithub** [comment]
#### k.hara.pg commented on 2015-09-01T12:53:36Z



````markdown
This is a problem in the implementation of instance cache. None of old versions did support it.

(In reply to Vladimir Panteleev from comment #1)
> This appears to be a regression.
> 
> Introduced by https://github.com/D-Programming-Language/dmd/pull/544

No, before that PR, there's no attribute inference for template functions, so foo!T() didn't see the hasElaborateAssign!T instantiation in its body.

Change to major.
````
