### PR TITLE
stringtable.d: add some const

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by wilzbach** [comment]
SemaphoreCI failed with:

```
Test compilable/teststdint.d failed.  The logged output:
../generated/linux/release/64/dmd -conf= -m64 -Icompilable  -fPIC  -odtest_results/compilable -oftest_results/compilable/teststdint_0.o  -c compilable/teststdint.d 
compilable/teststdint.d(211): Error: static assert:  `"_Z10int_fast16i" == "_Z10int_fast16l"` is false
```

Looks spurious though. Restarted.

**Comment by wilzbach** [comment]
This was introduced in https://github.com/dlang/dmd/pull/8252
