### PR TITLE
Add -unittest=rootonly and -unittest=first flags

### PR DESCRIPTION
**Pull request by alexandrumc**
The default instantiation strategy (no `-unittest`) is to prefer the template instances that are instantiated in non-root modules in order to minimize the binary size and the compilation time (there are fewer symbols which require semantic analysis). 

However, when the `-unittest` flag is enabled, the strategy is to prefer the template instances that are instantiated in root modules (this leads to larger binaries and compilation times but guarantees no link-time failures).

To avoid the compilation time and the binary size increase I propose two new flavors of the `-unittest` flag which use the default instantiation strategy and provide more flexibility in testing. 

`-unittest=rootonly` enables only the `version(unittest) {}` and the `unittest {}` blocks that reside inside the root modules. 

`-unittest=first` enables only the `version(unittest) {}` and the `unittest {}` blocks that reside in the _first_ root module provided in the command line. This is useful if one wants to test only a single module but also has to provide other root modules for linking reasons.

### CODE REVIEW

File: src/dmd/dmodule.d [hunk 1]
```diff
@@ -426,6 +426,7 @@ extern (C++) final class Module : Package
     Strings contentImportedFiles; // array of files whose content was imported
     int needmoduleinfo;
     int selfimports;            // 0: don't know, 1: does not, 2: does
+    bool rootChief;             // first root module in the command line
```
Comment (ibuclaw) [inline src/dmd/dmodule.d]: Needs header update

File: src/dmd/globals.d [hunk 2]
```diff
@@ -148,6 +148,8 @@ extern (C++) struct Param
     DiagnosticReporting useDeprecated = DiagnosticReporting.inform;  // how use of deprecated features are handled
     bool stackstomp;            // add stack stomping code
     bool useUnitTests;          // generate unittest code
+    bool UnittestRootOnly;      // generate unittest code only for root modules
+    bool UnittestFirstRootOnly; // generate unittest code only for the first root module
```
Comment (ibuclaw) [inline src/dmd/globals.d]: It would appear that this is better as an enum, instead of three mutually exclusive fields.

**Comment by WalterBright** [comment]
> To avoid the compilation time and the binary size increase

Do we really need to solve this problem? Adding more and more flags and conditions just makes things confusing. Unittest should be as simple as practical.

**Comment by Geod24** [comment]
Agreed with @WalterBright . I don't think exposing the complexities of template instantiation is a step forward.

**Comment by atilaneves** [comment]
I think we need to fix this problem because one of D's strategic advantages are fast compile times, but they suffer immediately when `-unittest` is used.

**Comment by schveiguy** [comment]
The issue with unittests is simpler IMO. We simply should not compile unittests in imported modules period. This is exactly how it works for non templated unittests. This is where the slowdown comes from.

See previous work here: https://github.com/dlang/dmd/pull/8124

**Comment by atilaneves** [comment]
> The issue with unittests is simpler IMO. We simply should not compile unittests in imported modules period. This is exactly how it works for non templated unittests. This is where the slowdown comes from.

That's not what @alexandrumc found.

**Comment by schveiguy** [comment]
> That's not what @alexandrumc found.

What did he find? I found that non-templated unittests were not semantically analyzed. I had thought they were, but discovered it only happens for templates.

**Comment by ibuclaw** [comment]
@schveiguy rereading the comment and taking it at face value. I understood it to be the following scenario.

Module A instantiates template FN in normal code, but compilation does not generate code for it because imported module B also instantiates the template with the same constraints. 
If compiling with `-unittest` however, all modules generate code for FN. (I think I remember another command line switch that can invoke the same behaviour... `-cov`?).

Though I disagree that the above I described would increase binary size, as duplicates are discarded at link time.

There's a bug report somewhere that explains the historical why it is necessary to always generate code if unittests are being compiled too. However off the top of my head, I'd say it makes more sense to do this when `-main` is used as well.

**Comment by alexandrumc** [comment]
> If compiling with `-unittest` however, all modules generate code for FN. (I think I remember another command line switch that can invoke the same behaviour... `-cov`?).

Yes, that's exactly why it takes more time to compile.

> Though I disagree that the above I described would increase binary size, as duplicates are discarded at link time.

Yeah, that's probably correct. It's my mistake. Now I realize that it's not the binary size which is increased but the obj/lib files. (e.g. when Phobos is compiled for unit testing, it is compiled one module at a time using `-unittest` flag and then the .o-s are bound together into a .lib; however, each object file was compiled with `-unittest` and has its own object code for its template instantiations, even if the same code/instances might be present in other modules; since there's no linker, the .lib will contain multiple TIs of the same type so its size will increase)

> There's a bug report somewhere that explains the historical why it is necessary to always generate code if unittests are being compiled too.

I couldn't think of another reason than to avoid link-time errors.

**Comment by schveiguy** [comment]
The problem that I've seen is that instantiated templates included their unittests even if they were imports. And it was really the semantic analysis that caused the slowdown. I'm trying to verify what actually happens with when I remember happening, but my various compiler installations are not all working.

There were cases where unittests were being semantically analyzed of imported templates, which in turn imported more stuff and then blew up into a huge problem. But I can't remember or re-prove what was happening. At this point, it appears that templates that are not instantiated locally do not include instantiated unittest semantic analysis, which is good. In the past it was included, but I don't know when that was stopped.

Imported templates that are instantiated locally still run unittests of those templates. I still think that should be stopped, there's no reason to test imported types that have documenting unittests just because you instantiated them locally.

**Comment by schveiguy** [comment]
OK, so the analysis is still done in certain cases. So for example:

```D
module mod1;

struct S()
{
  unittest { pragma(msg, "analyzed"); }
}
version(test1) alias sinst = S!();
version(test2) void foo(S!() s) {}
```
And the importing module:

```D
import mod1;
version(test3) alias sinst = S!();
void main() {}
```

So let's compile mod1 like this:

```
dmd -c mod1.d
```

No instantiations, no unittests.

What happens when you compile main.d?

test case | Compilation output | Runtime output | Unittest Analyzed | Unittest Included
---------|---------------------|-----------------|------------------|---------------
`dmd -version=test1 main.d mod1.o` | (nothing) | (nothing) | No | No
`dmd -version=test2 main.d mod1.o` | analyzed | (nothing) | Yes | No
`dmd -version=test3 main.d mod1.o` | analyzed | 1 Unittests passed | Yes | Yes

So IMO, the most damaging one is test2. You are semantically analyzing the unittest, which means importing and compiling all it requires without actually including the unittest.

test3 is also not ideal, I don't think there's any reason to run unittests of imported modules period.

**Comment by alexandrumc** [comment]
> OK, so the analysis is still done in certain cases. So for example:
> 
> ```d
> module mod1;
> 
> struct S()
> {
>   unittest { pragma(msg, "analyzed"); }
> }
> version(test1) alias sinst = S!();
> version(test2) void foo(S!() s) {}
> ```
> 
> And the importing module:
> 
> ```d
> import mod1;
> version(test3) alias sinst = S!();
> void main() {}
> ```
> 
> So let's compile mod1 like this:
> 
> ```
> dmd -c mod1.d
> ```
> 
> No instantiations, no unittests.
> 
> What happens when you compile main.d?
> 
> test case	Compilation output	Runtime output	Unittest Analyzed	Unittest Included
> `dmd -unittest -version=test1 main.d mod1.o`	(nothing)	(nothing)	No	No
> `dmd -unittest -version=test2 main.d mod1.o`	analyzed	(nothing)	Yes	No
> `dmd -unittest -version=test3 main.d mod1.o`	analyzed	1 Unittests passed	Yes	Yes
> So IMO, the most damaging one is test2. You are semantically analyzing the unittest, which means importing and compiling all it requires without actually including the unittest.
> 
> test3 is also not ideal, I don't think there's any reason to run unittests of imported modules period.

Thanks for the detailed explanation. I've compiled (the same way you did) using the changes in this PR (with `-unittest=rootonly` and with `-unittest=first`) and the unittest is not analyzed or included in any of the 3 cases. That's because the unittests in non-root modules are not even parsed. Could you please try it too?

**Comment by schveiguy** [comment]
> That's because the unittests in non-root modules are not even parsed.

Yes, but I'm saying that should be the way it ALWAYS is, not just behind a switch.

**Comment by schveiguy** [comment]
I suppose I should clarify a bit. Yes, I agree that only root unittests should be compiled. In response to Walter, that *is* the simplest possible solution. I can't seen any use case to compile unit tests in imported modules that aren't being included as part of the compilation unit.

I understand that this PR does this for a specialized switch -- I think it should be always. I don't think the `first` option needs to exist, you can already separately compile files with different switches.

And I don't buy that the emitting of the compiled code to object files is the problem, I think it's the semantic analysis. This PR solves both, but I think a simpler solution could solve the most expensive one.

**Comment by schveiguy** [comment]
> `-unittest=rootonly` enables only the `version(unittest) {}` and the `unittest {}` blocks that reside inside the root modules.

BTW, version(unittest) should NOT be turned off if -unittest or -unittest=anything is on. It's too dangerous to do this.

**Comment by schveiguy** [comment]
> This PR solves both, but I think a simpler solution could solve the most expensive one.

I guess you solve the semantic analysis you solve both :) So yeah, my complaint really just falls back on, why don't we always do what `-unittest=rootonly` does in this PR.

**Comment by ibuclaw** [comment]
Let's see what the testsuite says first before making it the default.

**Comment by alexandrumc** [comment]
> > `-unittest=rootonly` enables only the `version(unittest) {}` and the `unittest {}` blocks that reside inside the root modules.
> 
> BTW, version(unittest) should NOT be turned off if -unittest or -unittest=anything is on. It's too confusing/disruptive to do this.

`version (unittest)` usually covers top-level templates. If the `version (unittest)` blocks not turned off, the semantic analysis will have much more work to do, so the compile-time will increase.

**Comment by Geod24** [comment]
> the semantic analysis will have much more work to do

Only if those templates are instantiated, no ?

**Comment by alexandrumc** [comment]
> > the semantic analysis will have much more work to do
> 
> Only if those templates are instantiated, no ?

Yes, but that's not so uncommon to see. This is why I changed all the `version (unittest)`s from Phobos and DRuntime to `version (StdUnittest)` and `version (CoreUnittest)`. I'm sure no one wants to have hundreds of symbols analyzed (used for unit testing the standard library and the runtime) when he tests his own project.

**Comment by alexandrumc** [comment]
> Let's see what the testsuite says first before making it the default.

I've changed the `-unittest=rootonly` to default. As expected, everything fails because templates are no longer instantiated in root modules if the same types of instantiations are already present in non-root modules. So in my opinion, the issue is not the functionality of the flag, it's the way projects are compiled for unit testing. 

This is why I think this flag shouldn't directly replace `-unittest`. I think that at some point `-unittest` should be deprecated and be completely replaced by `-unittest=rootonly`, but that only if the users change the way they do unit testing for their projects (if they are interested in faster compilation times). Maybe that won't ever happen, but I still think there are some people interested in this kind of behavior and this new flavor would help them.

**Comment by Geod24** [comment]
Those failures seems to indicate another problem. Just looking at two random failures:
```
sh: line 1: 18715 Illegal instruction     (core dumped) generated/runnable/issue16995_4 > generated/92f0d3bd10dd5a60e69655bfd0ee7a981baf50fa83f09b08cfbb8f525a96a11 2>&1
 ... runnable/issue16995.d          -unittest  -fPIC (-O -inline -release)
Test runnable/issue16995.d failed.  The logged output:
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC  -odgenerated/runnable -c  runnable/issue16995.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC  -odgenerated/runnable -c  runnable/imports/module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC  -odgenerated/runnable -c  runnable/imports/another_module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64  -fPIC  -odgenerated/runnable -ofgenerated/runnable/issue16995_0 generated/runnable/issue16995.o generated/runnable/module_with_tests.o generated/runnable/another_module_with_tests.o
generated/runnable/issue16995_0

/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -odgenerated/runnable -c  runnable/issue16995.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -odgenerated/runnable -c  runnable/imports/module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -odgenerated/runnable -c  runnable/imports/another_module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64  -fPIC  -odgenerated/runnable -ofgenerated/runnable/issue16995_1 generated/runnable/issue16995.o generated/runnable/module_with_tests.o generated/runnable/another_module_with_tests.o
generated/runnable/issue16995_1

/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -inline -odgenerated/runnable -c  runnable/issue16995.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -inline -odgenerated/runnable -c  runnable/imports/module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -inline -odgenerated/runnable -c  runnable/imports/another_module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64  -fPIC  -odgenerated/runnable -ofgenerated/runnable/issue16995_2 generated/runnable/issue16995.o generated/runnable/module_with_tests.o generated/runnable/another_module_with_tests.o
generated/runnable/issue16995_2

/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -inline -odgenerated/runnable -c  runnable/issue16995.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -inline -odgenerated/runnable -c  runnable/imports/module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -O -inline -odgenerated/runnable -c  runnable/imports/another_module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64  -fPIC  -odgenerated/runnable -ofgenerated/runnable/issue16995_3 generated/runnable/issue16995.o generated/runnable/module_with_tests.o generated/runnable/another_module_with_tests.o
generated/runnable/issue16995_3

/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -release -odgenerated/runnable -c  runnable/issue16995.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -release -odgenerated/runnable -c  runnable/imports/module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC -release -odgenerated/runnable -c  runnable/imports/another_module_with_tests.d
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64  -fPIC  -odgenerated/runnable -ofgenerated/runnable/issue16995_4 generated/runnable/issue16995.o generated/runnable/module_with_tests.o generated/runnable/another_module_with_tests.o
generated/runnable/issue16995_4


==============================
Test runnable/issue16995.d failed: expected rc == 0, exited with rc == 132
```
This test does not use templates:
- https://github.com/dlang/dmd/blob/master/test/runnable/issue16995.d
- https://github.com/dlang/dmd/blob/master/test/runnable/imports/module_with_tests.d
- https://github.com/dlang/dmd/blob/master/test/runnable/imports/another_module_with_tests.d
Modules are compiled separately and linked together, no template is involved, and the compiler produces a corrupted binary (hence the exit code).

```
 ... runnable/test11745.d           -unittest  -fPIC ()
Test runnable/test11745.d failed.  The logged output:
/media/disk1/braddr/sandbox/at-client/pull-3987706-Linux_64_64/dmd/generated/linux/release/64/dmd -conf= -m64 -Irunnable -unittest  -fPIC  -odgenerated/runnable -ofgenerated/runnable/test11745_0  runnable/test11745.d runnable/imports/test11745b.d 
generated/runnable/test11745_0.o: In function `_Dmain':
runnable/imports/test11745b.d:(.text._Dmain[_Dmain]+0xa): undefined reference to `_D7imports10test11745b16__unittest_L8_C9FZv'
runnable/imports/test11745b.d:(.text._Dmain[_Dmain]+0xf): undefined reference to `_D7imports10test11745b17__unittest_L14_C1FZv'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1


==============================
Test runnable/test11745.d failed: expected rc == 0, exited with rc == 1
```
Likewise, this test doesn't involve templates:
- https://github.com/dlang/dmd/blob/master/test/runnable/test11745.d
- https://github.com/dlang/dmd/blob/master/test/runnable/imports/test11745b.d
And as can be seen in the output, `imports.test11745b` is a root module.

File: src/dmd/mars.d [hunk 3]
```diff
@@ -2306,7 +2306,11 @@ bool parseCommandLine(const ref Strings arguments, const size_t argc, ref Param
                 goto Lerror;
         }
         else if (arg == "-unittest")
-            params.useUnitTests = true;
```
Comment (Geod24) [inline src/dmd/mars.d]: @alexandrumc : Here is your bug.
Either set `useUnitTests` whenever one of the three options is used, or completely eliminate it in favor of an enum. But you are removing the only place that sets it to `true` but still leaving conditions using it, that's bound to create bugs.

**Comment by Geod24** [comment]
> I'm sure no one wants to have hundreds of symbols analyzed (used for unit testing the standard library and the runtime) when he tests his own project.

[You'd be surprised](https://github.com/dlang/dub/issues/1735#issuecomment-508995546).

**Comment by schveiguy** [comment]
> `version (unittest)` usually covers top-level templates. If the `version (unittest)` blocks not turned off, the semantic analysis will have much more work to do, so the compile-time will increase.

Yes, and that's on the library developer to design properly. Note that a library author could include unittesting facilities for their library in case you want to integration test your project with their library. Or it might be something that's contained into one module for use in testing several modules, and only imported inside unittests.

There are definitely ways to use version(unittest) that don't impact importing modules, and there are ways to do it badly. But we should not restrict the feature, especially when there are valid uses.

File: src/dmd/globals.d (hunk 2 above)
Comment (alexandrumc) [reply src/dmd/globals.d]: Thanks!

File: src/dmd/mars.d (hunk 3 above)
Comment (alexandrumc) [reply src/dmd/mars.d]: Thanks!

**Comment by RazvanN7** [comment]
This seems to be outdated, given the recent template emission fixes.
