### PR TITLE
fix #21630: `enum` and `alias` ignored on runtime foreach loop variables

### LINKED ISSUE #21630: `enum` and `alias` ignored on runtime foreach loop variables
https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1010.md#proposal-1-allow-enum-and-alias-variables-for-unrolled-foreach-statements

> Currently, it is an error to use alias or enum on a regular foreach loop:
>
> ```d
> foreach (enum i; 0 .. 3){ ... } // error
> ```

As monkyyy points out, this check is in fact missing in DMD for `foreach` range statements. (It correctly gave an error with my original implementation inside my own frontend, but DMD handles the variable storage classes differently during lowering, so the same implementation does not work.)

### PR DESCRIPTION
**Pull request by tgehr**
Fixes https://github.com/dlang/dmd/issues/21630 . (Additionally adds tests for the existing checks in the analysis of `ForeachStatement`.)

### CODE REVIEW

**Review by ntrel — APPROVED** [review]

**Comment by ntrel** [comment]
Looks like this breaks static RangeForeach:
```
compilable/json.d(136): Error: cannot declare `enum` loop variables for non-unrolled foreach
static foreach(enum i; 0..3)
                       ^
```

**Comment by tgehr** [comment]
oops

**Comment by tgehr** [comment]
Closing in favor of https://github.com/dlang/dmd/pull/21633

**Comment by tgehr** [comment]
I guess alternatively could remove the storage classes during the static foreach lowering.

**Comment by tgehr** [comment]
With the new patch the problem should be gone.

**Comment by Bolpat** [comment]
> With the new patch the problem should be gone.

I don’t know if your implementation already does that, but it would be really nice if the indicator pointed at the offending keyword (`alias` or `enum`) and if there are several, one error message suffices.

Also, maybe give the error a supplement that says “use `static foreach` instead”. It’s very likely what the programmer intended.

When your PR gets merged, you’re absolutely free to close mine.

**Comment by tgehr** [comment]
Now `-vcg-ast` tests fail because it removes the storage class from the output.

**Comment by tgehr** [comment]
Hopefully the `-vgc-ast` issue is addressed too now.

> > With the new patch the problem should be gone.
> 
> I don’t know if your implementation already does that, but it would be really nice if the indicator pointed at the offending keyword (`alias` or `enum`) and if there are several, one error message suffices.
> 
> Also, maybe give the error a supplement that says “use `static foreach` instead”. It’s very likely what the programmer intended.
> ...

Ideally yes, though I think this is a different issue. Note that there is already this check, that works the same way:
https://github.com/dlang/dmd/blob/stable/compiler/src/dmd/statementsem.d#L879-L889

Feel free to open a separate enhancement request to address the diagnostics quality. IIRC when I originally added the message, columns were not even tracked yet in the compiler.

**Comment by tgehr** [comment]
Still failures related to json and vcg-ast, not sure how to reproduce. I cannot really spend a lot of time on this right now, I had thought this is a quick fix.

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -17757,10 +17757,11 @@ void lowerNonArrayAggregate(StaticForeach sfe, Scope* sc)
     Parameters*[3] pparams = [new Parameters(), new Parameters(), new Parameters()];
     foreach (i; 0 .. nvars)
     {
-        foreach (params; pparams)
+        foreach (j, params; pparams)
         {
             auto p = sfe.aggrfe ? (*sfe.aggrfe.parameters)[i] : sfe.rangefe.param;
-            params.push(new Parameter(aloc, p.storageClass, p.type, p.ident, null, null));
+            auto storageClass = j == 2 ? p.storageClass & ~STC.manifest & ~STC.alias_ : p.storageClass;
```
Comment (ibuclaw) [inline compiler/src/dmd/expressionsem.d]:
```suggestion
            auto storageClass = j == 2 ? p.storageClass & ~(STC.manifest | STC.alias_) : p.storageClass;
```
Choose whichever you think is more understandable.

Comment (tgehr) [reply compiler/src/dmd/expressionsem.d]: I don't have a strong preference. If the disjunctive form is more idiomatic in the DMD source I can use that one. (Also the bigger issue was that the condition is inverted).

**Comment by tgehr** [comment]
The failure seems unrelated:

```d
// https://issues.dlang.org/show_bug.cgi?id=3004
/*
REQUIRED_ARGS: -ignore -v
TRANSFORM_OUTPUT: remove_lines("^(predefs|binary|version|config|DFLAG|parse|import|\(imported|semantic|entry|library|function  object|function  core|\s*$)")
TEST_OUTPUT:
---
pragma    GNU_attribute (__error)
pragma    GNU_attribute (__error)
code      test3004
function  test3004.test
---
*/

extern(C) int printf(char*, ...);

pragma(GNU_attribute, flatten)
void test() { printf("Hello GNU world!\n".dup.ptr); }

pragma(GNU_attribute, flatten);
```

```
Test 'compilable/test3004.d' failed: 
expected:
----
pragma    GNU_attribute (__error)
pragma    GNU_attribute (__error)
code      test3004
function  test3004.test
----
actual:
----
pragma    GNU_attribute (__error)
pragma    GNU_attribute (__error)
inline scan test3004
code      test3004
function  test3004.test
----
diff:
----
 pragma    GNU_attribute (__error)
 pragma    GNU_attribute (__error)
+inline scan test3004
 code      test3004
 function  test3004.test
----
```

Not sure what `inline scan test3004` means.

**Comment by tgehr** [comment]
@dkorpel @MoonlightSentinel It seems you added the output transformation and expected output. Any idea why an unexpected `inline scan test3004` might appear here?

**Comment by rainers** [comment]
> @dkorpel @MoonlightSentinel It seems you added the output transformation and expected output. Any idea why an unexpected `inline scan test3004` might appear here?

The error is indeed unrelated and happens on stable, too: it needs the commit https://github.com/dlang/dmd/commit/c9030ed323956b4f82ee62ef6ed2d7518ae02708 currently only on master. There were some follow-up changes, too, but I think it can be cherry picked to stable.

AFAICT @dkorpel will merge master to stable before the next release, so you can also rebase this on master to avoid the issue.

**Comment by ibuclaw** [comment]
> > @dkorpel @MoonlightSentinel It seems you added the output transformation and expected output. Any idea why an unexpected `inline scan test3004` might appear here?
> 
> The error is indeed unrelated and happens on stable, too: it needs the commit https://github.com/dlang/dmd/commit/c9030ed323956b4f82ee62ef6ed2d7518ae02708 currently only on master. There were some follow-up changes, too, but I think it can be cherry picked to stable.
> 
> AFAICT @dkorpel will merge master to stable before the next release, so you can also rebase this on master to avoid the issue.

Failure was introduced by e33c664. So a merge went wrong.

**Comment by tgehr** [comment]
Thanks! Rebased to master.

**Review by thewilsonator — APPROVED** [review]

**Comment by tgehr** [comment]
Is master broken too?

It seems for buildkite the first error is:
```
std/array.d(1138): Error: template instance `_d_newarrayU!E` template `_d_newarrayU` is not defined, did you mean _d_newarrayT?
                ret = _d_newarrayU!E(size, isShared);
```
And for DAutoTest there seem to be parser errors related to `=>` function syntax.

In both cases it seems unlikely that my pull request broke them.

**Comment by ibuclaw** [comment]
> Is master broken too?
> 
> It seems for buildkite the first error is:
> ```
> std/array.d(1138): Error: template instance `_d_newarrayU!E` template `_d_newarrayU` is not defined, did you mean _d_newarrayT?
>                 ret = _d_newarrayU!E(size, isShared);
> ```
> And for DAutoTest there seem to be parser errors related to `=>` function syntax.
> 
> In both cases it seems unlikely that my pull request broke them.

Did you rebase against current head?

https://github.com/dlang/dmd/commit/c397436871bfb8051e2a3d4989cbfd5d87b195c9

All I see in master are what look like timed out failures in Azure and GHA/FreeBSD.

**Comment by ibuclaw** [comment]
The chance of failure caused by this PR is not zero.
```
std/array.d(1138): Error: template instance `_d_newarrayU!E` template `_d_newarrayU` is not defined, did you mean _d_newarrayT?
                ret = _d_newarrayU!E(size, isShared);
                      ^
std/array.d(1000): Error: template instance `std.array.arrayAllocImpl!(false, ulong[], ulong)` error instantiating
    return arrayAllocImpl!(false, T, ST)(sizes);
                                        ^
std/array.d(126):        instantiated from here: `uninitializedArray!(ulong[], const(ulong))`
        auto result = (() @trusted => uninitializedArray!(Unqual!E[])(length))();
                                                                     ^
std/meta.d(964):        instantiated from here: `array!(Result)`
        static foreach (size_t i, el; iter.array)
                                          ^
std/range/package.d(1100):        instantiated from here: `aliasSeqOf!(Result(0LU, 2LU))`
                        Result(staticMap!(saveI, aliasSeqOf!(R.length.iota)));
                                                 ^
std/bitmanip.d(2655):        instantiated from here: `chain!(Result, FilterResult!(__lambda_L2661_C26, Result))`
        return chain(
                    ^
std/meta.d(964): Error: CTFE failed because of previous errors in `array`
        static foreach (size_t i, el; iter.array)
                                          ^
std/meta.d(964): Error: CTFE failed because of previous errors in `array`
        static foreach (size_t i, el; iter.array)
                                          ^
```

And
```
std/path.d(1679):        instantiated from here: `chain!(ByCodeUnitImpl, OnlyResult!char, ByCodeUnitImpl)`
        return chain(r1[0 .. pos].byUTF!CR, sep, r2.byUTF!CR);
                    ^
std/path.d(1478):        instantiated from here: `chainPath!(char[], const(char)[])`
        auto r = chainPath(buf[0 .. pos], segment);
                          ^
std/path.d(1496):        instantiated from here: `buildPath!(const(char)[][])`
    return buildPath!(typeof(paths))(paths);
                                    ^
std/file.d(140):        instantiated from here: `buildPath!char`
        fileName = text(buildPath(tempDir(), base), thisProcessID);
                                 ^
std/path.d(1480): Error: invalid `foreach` aggregate `r` of type `Result`
        foreach (c; r)
        ^
std/path.d(1480):        `foreach` works with input ranges (implementing `front` and `popFront`), aggregates implementing `opApply`, or the result of an aggregate's `.tupleof` property
std/path.d(1480):        https://dlang.org/phobos/std_range_primitives.html#isInputRange
```

**Comment by ibuclaw** [comment]
I noticed that the last buildkite run used stable as the target branch when cloning Phobos.

Related PR https://github.com/dlang/phobos/pull/10819

Not convinced that it introduced something, as `_d_newarrayU` is publicly imported into every module.

https://github.com/dlang/dmd/blob/bc6dd9d9f6be12274ba402e9dab7f8aac011efc9/druntime/src/object.d#L4795

**Comment by ibuclaw** [comment]
> I noticed that the last buildkite run used stable as the target branch when cloning Phobos.
> 
> Related PR https://github.com/dlang/phobos/pull/10819
> 
> Not convinced that it introduced something, as `_d_newarrayU` is publicly imported into every module.
> 

Ah, it does matter, because https://github.com/dlang/dmd/pull/21525
