### PR TITLE
Fix Issue 23827 - IsExpression allows Identifier outside static if/assert

### PR DESCRIPTION
**Pull request by ntrel**
Bug introduced in #10939.

### CODE REVIEW

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
Please update the c++ header files.

**Comment by ntrel** [comment]
```
compilable/compile1.d(619): Error: static assert:  `0` is false
```
