### ISSUE TITLE
make target doc compile error: mach_header conflicts with other

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#17368]
### CC List

* Seb

### Description

````markdown
In v2.081.1 of druntime the following error messages are thrown when making with

> make -f posix.mak doc

src/rt/sections_osx_x86_64.d(122): Error: core.sys.darwin.mach.loader.mach_header at src/core/sys/darwin/mach/loader.d(13) conflicts with core.sys.darwin.mach.getsect.mach_header at src/core/sys/darwin/mach/getsect.d(228)
src/rt/sections_osx_x86_64.d(170): Error: cannot interpret SEG_DATA at compile time
src/rt/sections_osx_x86_64.d(170): Error: cannot interpret SECT_DATA at compile time
src/rt/sections_osx_x86_64.d(171): Error: cannot interpret SEG_DATA at compile time
src/rt/sections_osx_x86_64.d(171): Error: cannot interpret SECT_BSS at compile time
src/rt/sections_osx_x86_64.d(172): Error: cannot interpret SEG_DATA at compile time
src/rt/sections_osx_x86_64.d(172): Error: cannot interpret SECT_COMMON at compile time
src/rt/sections_osx_x86_64.d(174): Error: core.sys.darwin.mach.loader.mach_header at src/core/sys/darwin/mach/loader.d(13) conflicts with core.sys.darwin.mach.getsect.mach_header at src/core/sys/darwin/mach/getsect.d(228)


I was able to track it down with `git bisect` to this commit:
https://github.com/dlang/druntime/commit/0d7be1427e7c4ef53e8baf9e26b4916a3ea18542

v2.080.1 works fine.

Please let me know if there is anything I can do.
````

**Comment by dlangBugzillaToGithub** [comment]
#### greensunny12 commented on 2018-07-14T12:52:55Z



````markdown
Have you tried building the docs from dlang.org? The individual doc targets have been deprecated for a very long time already.
````

**Comment by dlangBugzillaToGithub** [comment]
#### timosesu commented on 2018-07-15T08:22:11Z



````markdown
(In reply to Seb from comment #1)
> Have you tried building the docs from dlang.org? The individual doc targets
> have been deprecated for a very long time already.

Yes, I tried building the verbatim version. That worked on a linux machine, but failed on my macOS.

make -f posix.mak -j8 html phobos-prerelease-verbatim

During the make process it tries to compile the druntime with doc as target, I believe.
````
