### PR TITLE
fix #22323 - error "cannot get frame pointer" with AA in struct literal

### LINKED ISSUE #22323: [Regression master]  error "cannot get frame pointer" with AA in struct literal
copied from https://github.com/ldc-developers/ldc/issues/5038:

compiling with `-preview=dip1000`:
```D
struct Schema { int[int] tables; }
struct S(Schema s) {
    void g() { cast(void)s.tables; }
}
auto makeSchema() => Schema([0: 0]);
alias Row = S!(makeSchema());
```
yields
```
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
                                ^
test.d(5): Error: cannot get frame pointer to `ldcfail.makeSchema`
    auto makeSchema() => Schema([0: 0]);
```
Works with dmd 2.111.0.

### PR DESCRIPTION
**Pull request by rainers**
deep copy manifest constant if it contains AA literal, so that it runs semantic again on lowered code

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
target stable so that LDC can pick this up. otherwise looks good.

**Comment by thewilsonator** [comment]
thanks

**Comment by rainers** [comment]
> target stable so that LDC can pick this up. otherwise looks good.

ok, rebased to stable.
