### ISSUE TITLE
Nested class unable to resolve outer class variables in certain scenarios

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#17763]
### CC List

* ag0aep6g
* Walter Bright (@WalterBright)
* 
* Seb
* Boris-Barboris
* RazvanN

### Description

````markdown
This is one of the corner cases that I could reduce.

bool frop(int f) {return true;}
class Bar {
  int zoo;
  class Foo {
    bool foo() {
      return (zoo).frop();
    }
  }
}

$  dmd -c test.d
test.d(6): Error: need 'this' for 'zoo' of type 'int'
````

**Comment by dlangBugzillaToGithub** [comment]
#### puneet commented on 2016-06-29T02:17:13Z



````markdown
Another reduced case:

class Foo {
  class FooInner {}
}
class Bar: Foo {
  byte foo;
  class BarInner(T): Foo.FooInner {
    byte zoo() {
      return foo;
    }
  }
  alias BarInnerThis = BarInner!Bar;
}

$ dmd -c test.d
test.d(8): Error: need 'this' for 'foo' of type 'byte'
````

**Comment by dlangBugzillaToGithub** [comment]
#### ismailsiege commented on 2019-05-07T19:22:46Z



````markdown
Analogous case that does not work in dmd 2.086.0, but works in 2.085.0:

class Base
{
    class BaseInner {}
}

final class Derived: Base
{
    bool someMethod() { return false; }
    
    final class DerivedInner: BaseInner
    {
     	 void func()
         {
             pragma(msg, typeof(this.outer)); // prints "Derived"
             someMethod();
         }
    }
}

void main() {}


compiler output:
Derived
onlineapp.d(17): Error: this for someMethod needs to be type Derived not type onlineapp.Base
````

**Comment by dlangBugzillaToGithub** [comment]
#### er.krali commented on 2019-06-17T08:31:45Z



````markdown
Shouldn't this bug be marked now as a regression? Checking the code in the previous comment:

Up to      2.067.1: Success with output: Base
2.068.2 to 2.085.1: Success with output: Derived
Since      2.086.0: Failure with output:
-----
Derived
onlineapp.d(16): Error: `this` for `someMethod` needs to be type `Derived` not type `onlineapp.Base`
-----
````

**Comment by dlangBugzillaToGithub** [comment]
#### bugzilla (@WalterBright) commented on 2020-02-13T08:40:11Z



````markdown
(In reply to Puneet Goel from comment #0)
> This is one of the corner cases that I could reduce.

-       return (zoo).frop();
+       return frop(zoo);

Note with the above change it compiles successfully.
````

**Comment by dlangBugzillaToGithub** [comment]
#### bugzilla (@WalterBright) commented on 2020-02-13T09:02:43Z



````markdown
These actually appear to be three separate issues.
````

**Comment by dlangBugzillaToGithub** [comment]
#### razvan.nitu1305 commented on 2021-02-24T13:08:42Z



````markdown
(In reply to Walter Bright from comment #4)
> (In reply to Puneet Goel from comment #0)
> > This is one of the corner cases that I could reduce.
> 
> -       return (zoo).frop();
> +       return frop(zoo);
> 
> Note with the above change it compiles successfully.

That specific case seems to be running fine with today's compiler.
````
