### ISSUE TITLE
PR #21001 introduces bug

### ISSUE THREAD

**Issue by ryuukk** [dlang/dmd#21094]
Introduced with PR #21001 

```
better_d/rt/fmt/package.d:467: Error: cannot use `final switch` on enum `upng_error` while it is being defined
    final switch (v) with(E)
    ^
```

repro:

`dmd -betterC app.d libtest.c`

- app.d
```D
import core.stdc.stdio;

import c = libtest;

string enum_to_str(E)(E v) if (is(E == enum))
{
    final switch (v) with(E)
    {
        static foreach (m; __traits(allMembers, E))
        {
    case mixin(m):
            return m;
        }
    }
}

extern(C) void main()
{
    auto str = enum_to_str(c.UPNG_EOK);

    printf("%.*s\n", cast(int) str.length, str.ptr);
}
```

- libtest.c
```C
typedef enum upng_error {
    UPNG_EOK            = 0, /* success (no error) */
    UPNG_ENOMEM         = 1, /* memory allocation failed */
    UPNG_ENOTFOUND      = 2, /* resource not found (file missing) */
    UPNG_ENOTPNG        = 3, /* image data does not have a PNG header */
    UPNG_EMALFORMED     = 4, /* image data is not a valid PNG image */
    UPNG_EUNSUPPORTED   = 5, /* critical PNG chunk type is not supported */
    UPNG_EUNINTERLACED  = 6, /* image interlacing is not supported */
    UPNG_EUNFORMAT      = 7, /* image color format is not supported */
    UPNG_EPARAM         = 8  /* invalid parameter to method call */
} upng_error;
```

**Comment by dkorpel** [comment]
Thanks for testing nightly builds!
