### ISSUE TITLE
DMD crashes for `auto[$] x;`

### ISSUE THREAD

**Issue by tim-dlang** [dlang/dmd#22881]
The new syntax `auto[$] x = []` has been introduced in PR https://github.com/dlang/dmd/pull/22802.

The following invalid code is accepted by the parser, but results in a crash in semantic analysis:
```D
auto[$] x;
```
Here is the output from gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555abefe6 in dmd.initsem.inferType(dmd.init.Initializer, dmd.dscope.Scope*).visit.VisitInitializer(dmd.init.Initializer) (__capture=0x7fffffffc590, init=0x0) at src/dmd/init.d:373
373	        final switch (init.kind)
```

Another example has a confusing error message:
```D
auto[$]* x=[];
```
DMD output:
```
testb.d(1): Error: undefined identifier `auto`
auto[$]* x=[];
    ^
testb.d(1): Error: variable `testb.x` - storage class `auto` has no effect if type is not inferred, did you mean `scope`?
auto[$]* x=[];
         ^
```

The changes to the spec should also update the grammar: https://dlang.org/spec/grammar.html#AutoDeclaration

**Comment by gulugulubing** [comment]
Ok, I'll check it. And as for the pointer problem, should we support something like:
```d
int[$] x = [1,2];
int[$]* y = &x;
```
Right now, it can't be compiled.

**Comment by tim-dlang** [comment]
I don't think support for `int[$]* y = &x;` would be needed. That is probably not common.
I only checked `auto[$]* x=[];`, because I saw the parser uses normal declaration parsing for these auto declaration.

**Comment by gulugulubing** [comment]
> I don't think support for `int[$]* y = &x;` would be needed. That is probably not common. I only checked `auto[$]* x=[];`, because I saw the parser uses normal declaration parsing for these auto declaration.

OK, but I am wondering: as for auto[$]*, should we emit a semantic error with a clear message or emit a syntax error at the parser stage?

**Comment by thewilsonator** [comment]
> emit a semantic error with a clear message

This.

**Comment by nordlow** [comment]
Should this issue be closed now that https://github.com/dlang/dmd/pull/22886 is merged?
